import type { TEventObject } from "src/types";

export const GREGORIAN_EVENTS: TEventObject[] = [
	{ holiday: false, month: 1, day: 1, base: "Global", title: "آغاز سال میلادی" },
	{ holiday: false, month: 1, day: 2, base: "Global", title: "روز جهانی گمرک" },
	{ holiday: false, month: 2, day: 4, base: "Global", title: "روز جهانی سرطان" },
	{ holiday: false, month: 2, day: 6, base: "Global", title: "روز جهانی مبارزه با ناقص‌سازی زنان" },
	{ holiday: false, month: 2, day: 20, base: "Global", title: "روز جهانی عدالت اجتماعی" },
	{ holiday: false, month: 2, day: 21, base: "Global", title: "روز جهانی زبان مادری" },
	{ holiday: false, month: 3, day: 8, base: "Global", title: "روز جهانی زنان" },
	{ holiday: false, month: 3, day: 22, base: "Global", title: "روز جهانی آب" },
	{ holiday: false, month: 3, day: 23, base: "Global", title: "روز جهانی هواشناسی" },
	{ holiday: false, month: 3, day: 24, base: "Global", title: "روز جهانی سل" },
	{ holiday: false, month: 4, day: 7, base: "Global", title: "روز جهانی سلامت" },
	{ holiday: false, month: 4, day: 22, base: "Global", title: "روز جهانی زمین پاک" },
	{ holiday: false, month: 4, day: 23, base: "Global", title: "روز جهانی کتاب و حق مؤلف" },
	{ holiday: false, month: 4, day: 25, base: "Global", title: "روز جهانی مالاریا" },
	{ holiday: false, month: 4, day: 27, base: "Global", title: "روز جهانی گرافیک" },
	{ holiday: false, month: 5, day: 1, base: "Global", title: "روز جهانی کارگر" },
	{ holiday: false, month: 5, day: 3, base: "Global", title: "روز جهانی آزادی مطبوعات" },
	{ holiday: false, month: 5, day: 5, base: "Global", title: "روز جهانی ماما" },
	{ holiday: false, month: 5, day: 8, base: "Global", title: "روز جهانی صلیب سرخ و هلال احمر" },
	{ holiday: false, month: 5, day: 15, base: "Global", title: "روز جهانی خانواده" },
	{ holiday: false, month: 5, day: 17, base: "Global", title: "روز جهانی ارتباطات و روابط عمومی" },
	{ holiday: false, month: 5, day: 18, base: "Global", title: "روز جهانی موزه و میراث فرهنگی" },
	{ holiday: false, month: 5, day: 29, base: "Global", title: "روز جهانی حافظان صلح ملل متحد" },
	{ holiday: false, month: 5, day: 31, base: "Global", title: "روز جهانی بدون دخانیات" },
	{ holiday: false, month: 6, day: 1, base: "Global", title: "روز جهانی والدین" },
	{ holiday: false, month: 6, day: 5, base: "Global", title: "روز جهانی محیط زیست" },
	{ holiday: false, month: 6, day: 10, base: "Global", title: "روز جهانی صنایع دستی" },
	{ holiday: false, month: 6, day: 12, base: "Global", title: "روز جهانی منع کار کودکان" },
	{ holiday: false, month: 6, day: 14, base: "Global", title: "روز جهانی اهدا خون" },
	{ holiday: false, month: 6, day: 14, base: "Global", title: "روز جهانی مادر" },
	{ holiday: false, month: 6, day: 17, base: "Global", title: "روز جهانی بیابان‌زدایی" },
	{ holiday: false, month: 6, day: 20, base: "Global", title: "روز جهانی پناهندگان" },
	{ holiday: false, month: 6, day: 26, base: "Global", title: "روز جهانی مبارزه با مواد مخدر" },
	{ holiday: false, month: 6, day: 26, base: "Global", title: "روز جهانی قربانیان خشونت" },
	{ holiday: false, month: 6, day: 26, base: "Global", title: "روز جهانی جمعیت" },
	{ holiday: false, month: 8, day: 1, base: "Global", title: "روز جهانی شیر مادر" },
	{ holiday: false, month: 8, day: 6, base: "Global", title: "انفجار بمب اتمی آمریکا در هیروشیما با بیش از ۱۶۰ هزار کشته و مجروح (۱۹۴۵ میلادی)" },
	{ holiday: false, month: 8, day: 12, base: "Global", title: "روز جهانی جوانان" },
	{ holiday: false, month: 8, day: 13, base: "Global", title: "روز جهانی چپ دستان" },
	{ holiday: false, month: 8, day: 19, base: "Global", title: "روز جهانی انسان دوستی" },
	{ holiday: false, month: 8, day: 19, base: "Global", title: "روز جهانی عکاسی" },
	{ holiday: false, month: 8, day: 21, base: "Global", title: "روز جهانی مسجد" },
	{ holiday: false, month: 9, day: 1, base: "Global", title: "روز جهانی صلح" },
	{ holiday: false, month: 9, day: 8, base: "Global", title: "روز جهانی با سوادی" },
	{ holiday: false, month: 9, day: 10, base: "Global", title: "روز جهانی جلوگیری از خودکشی" },
	{ holiday: false, month: 9, day: 21, base: "Global", title: "روز جهانی باسوادی و روز جهانی آلزایمر" },
	{ holiday: false, month: 9, day: 27, base: "Global", title: "روز جهانی جهانگردی" },
	{ holiday: false, month: 9, day: 30, base: "Global", title: "روز جهانی ناشنوایان" },
	{ holiday: false, month: 9, day: 30, base: "Global", title: "روز جهانی دریانوردی" },
	{ holiday: false, month: 10, day: 1, base: "Global", title: "روز جهانی سالمندان" },
	{ holiday: false, month: 10, day: 5, base: "Global", title: "روز جهانی جلوگیری از خودکشی" },
	{ holiday: false, month: 10, day: 8, base: "Global", title: "روز جهانی کودک" },
	{ holiday: false, month: 10, day: 9, base: "Global", title: "روز جهانی پست" },
	{ holiday: false, month: 10, day: 14, base: "Global", title: "روز جهانی استاندارد" },
	{ holiday: false, month: 10, day: 15, base: "Global", title: "روز جهانی نابینایان (عصای سفید)" },
	{ holiday: false, month: 10, day: 16, base: "Global", title: "روز جهانی غذا" },
	{ holiday: false, month: 10, day: 24, base: "Global", title: "روز ملل متحد و روز جهانی توسعه اطلاعات" },
	{ holiday: false, month: 10, day: 27, base: "Global", title: "روز جهانی میراث سمعی و بصری" },
	{ holiday: false, month: 10, day: 31, base: "Global", title: "روز جهانی شهرها" },
	{ holiday: false, month: 10, day: 31, base: "Global", title: "جشن هالووین" },
	{ holiday: false, month: 11, day: 6, base: "Global", title: "روز بین‌المللی پیشگیری از سوء استفاده از محیط زیست در جنگ و مناقشات مسلحانه" },
	{ holiday: false, month: 11, day: 10, base: "Global", title: "روز جهانی علم در خدمت صلح و توسعه" },
	{ holiday: false, month: 11, day: 14, base: "Global", title: "روز جهانی دیابت" },
	{ holiday: false, month: 11, day: 21, base: "Global", title: "روز جهانی تلویزیون" },
	{ holiday: false, month: 11, day: 25, base: "Global", title: "روز جهانی مبارزه با خشونت علیه زنان" },
	{ holiday: false, month: 11, day: 29, base: "Global", title: "روز جهانی همبستگی با مردم فلسطین" },
	{ holiday: false, month: 12, day: 1, base: "Global", title: "روز جهانی مبارزه با ایدز" },
	{ holiday: false, month: 12, day: 2, base: "Global", title: "روز جهانی لغو برده‌داری" },
	{ holiday: false, month: 12, day: 3, base: "Global", title: "روز جهانی معلولین" },
	{ holiday: false, month: 12, day: 7, base: "Global", title: "روز جهانی هواپیمایی" },
	{ holiday: false, month: 12, day: 10, base: "Global", title: "روز جهانی حقوق بشر" },
	{ holiday: false, month: 12, day: 11, base: "Global", title: "روز جهانی کوهستان" },
	{ holiday: false, month: 12, day: 18, base: "Global", title: "روز جهانی عاری از خشونت و افراطی‌گری" },
	{ holiday: false, month: 12, day: 18, base: "Global", title: "روز جهانی مهاجران" },
	{ holiday: false, month: 12, day: 25, base: "Global", title: "ولادت حضرت عیسی مسیح (ع)" }
] as const;
