import type { TEventObject } from "src/types";

export const HIJRI_EVENTS: TEventObject[] = [
	{ holiday: false, month: 1, day: 1, base: "IR Islam", title: "آغاز سال هجری قمری" },
	{ holiday: true, month: 1, day: 9, base: "IR Islam", title: "تاسوعای حسینی" },
	{ holiday: true, month: 1, day: 10, base: "IR Islam", title: "عاشورای حسینی" },
	{ holiday: false, month: 1, day: 11, base: "IR Islam", title: "روز تجلیل از اسرا و مفقودان" },
	{ holiday: false, month: 1, day: 12, base: "IR Islam", title: "شهادت امام زین‌العابدین (ع) (۹۵ ه‍.ق)" },
	{ holiday: false, month: 1, day: 25, base: "IR Islam", title: "شهادت امام زین‌العابدین (ع) (۹۵ ه‍.ق) به روایتی" },
	{ holiday: false, month: 2, day: 7, base: "IR Islam", title: "شهادت امام حسن مجتبی (ع) (۵۰ ه‍.ق) (به روایتی)" },
	{ holiday: false, month: 2, day: 7, base: "IR Islam", title: "روز بزرگداشت سلمان فارسی" },
	{ holiday: true, month: 2, day: 20, base: "IR Islam", title: "اربعین حسینی" },
	{ holiday: false, month: 2, day: 27, base: "IR Islam", title: "روز وقف" },
	{ holiday: true, month: 2, day: 28, base: "IR Islam", title: "رحلت حضرت رسول اکرم (ص) (۱۱ ه‍.ق) – شهادت امام حسن مجتبی (ع) (۵۰ ه‍.ق)" },
	{ holiday: true, month: 2, day: 30, base: "IR Islam", title: "شهادت امام رضا (ع) (۲۰۳ ه‍.ق)" },
	{ holiday: false, month: 3, day: 1, base: "IR Islam", title: "هجرت رسول اکرم (ص) از مکه به مدینه" },
	{ holiday: true, month: 3, day: 8, base: "IR Islam", title: "شهادت امام حسن عسکری (ع) (۲۶۰ ه‍.ق) و آغاز امامت حضرت ولی عصر (عج)" },
	{ holiday: false, month: 3, day: 12, base: "IR Islam", title: "ولادت حضرت رسول اکرم (ص) به روایت اهل سنت (۵۳ سال قبل از هجرت) - آغاز هفتهٔ وحدت" },
	{ holiday: true, month: 3, day: 17, base: "IR Islam", title: "ولادت حضرت رسول اکرم (ص) (۵۳ سال قبل از هجرت) و روز اخلاق و مهرورزی" },
	{ holiday: true, month: 3, day: 17, base: "IR Islam", title: "ولادت امام جعفر صادق (ع) مؤسس مذهب جعفری (۸۳ ه‍.ق)" },
	{ holiday: false, month: 4, day: 8, base: "IR Islam", title: "ولادت امام حسن عسگری (ع) (۲۳۲ ه‍.ق)" },
	{ holiday: false, month: 4, day: 10, base: "IR Islam", title: "وفات حضرت معصومه (س) (۲۰۱ ه‍.ق)" },
	{ holiday: false, month: 5, day: 5, base: "IR Islam", title: "ولادت حضرت زینب (س) (۵ ه‍.ق) و روز پرستار" },
	{ holiday: false, month: 5, day: 13, base: "IR Islam", title: "شهادت حضرت فاطمهٔ زهرا (س) (۱۱ ه‍.ق) به روایتی" },
	{ holiday: true, month: 6, day: 3, base: "IR Islam", title: "شهادت حضرت فاطمهٔ زهرا (س) (۱۱ ه‍.ق)" },
	{ holiday: false, month: 6, day: 13, base: "IR Islam", title: "سالروز وفات حضرت ام‌البنین (س) - روز تکریم مادران و همسران شهدا" },
	{ holiday: false, month: 6, day: 20, base: "IR Islam", title: "روز زن و مادر و ولادت حضرت فاطمهٔ زهرا (س) (سال هشتم قبل از هجرت)" },
	{ holiday: false, month: 6, day: 20, base: "IR Islam", title: "تولد امام خمینی (ره) رهبر کبیر انقلاب اسلامی (۱۳۲۰ ه‍.ق)" },
	{ holiday: false, month: 7, day: 1, base: "IR Islam", title: "ولادت امام محمد باقر (ع) (۵۷ ه‍.ق)" },
	{ holiday: false, month: 7, day: 3, base: "IR Islam", title: "شهادت امام علی النقی الهادی (ع) (۲۵۴ ه‍.ق)" },
	{ holiday: false, month: 7, day: 10, base: "IR Islam", title: "ولادت امام محمد تقی (ع) (۱۹۵ ه‍.ق)" },
	{ holiday: true, month: 7, day: 13, base: "IR Islam", title: "روز پدر و مرد و ولادت امام علی (ع) (۲۳ سال قبل از هجرت) – آغاز ایام‌البیض (اعتکاف)" },
	{ holiday: false, month: 7, day: 15, base: "IR Islam", title: "وفات حضرت زینب (س) (۶۲ ه‍.ق)" },
	{ holiday: false, month: 7, day: 15, base: "IR Islam", title: "تغییر قبلهٔ مسلمین از بیت‌المقدس به مکهٔ معظمه (۲ ه‍.ق)" },
	{ holiday: false, month: 7, day: 25, base: "IR Islam", title: "شهادت امام موسی کاظم (ع) (۱۸۳ ه‍.ق)" },
	{ holiday: true, month: 7, day: 27, base: "IR Islam", title: "مبعث حضرت رسول اکرم (ص) (۱۳ سال قبل از هجرت)" },
	{ holiday: false, month: 8, day: 3, base: "IR Islam", title: "ولادت امام حسین (ع) (۴ ه‍.ق) و روز پاسدار" },
	{ holiday: false, month: 8, day: 4, base: "IR Islam", title: "ولادت حضرت ابوالفضل العباس (ع) (۲۶ ه‍.ق) و روز جانباز" },
	{ holiday: false, month: 8, day: 5, base: "IR Islam", title: "ولادت امام زین‌العابدین (ع) (۳۸ ه‍.ق)" },
	{ holiday: false, month: 8, day: 11, base: "IR Islam", title: "ولادت حضرت علی اکبر (ع) (۳۳ ه‍.ق) و روز جوان" },
	{ holiday: true, month: 8, day: 15, base: "IR Islam", title: "ولادت حضرت قائم (عج) (۲۵۵ ه‍.ق) و روز جهانی مستضعفان" },
	{ holiday: false, month: 9, day: 10, base: "IR Islam", title: "وفات حضرت خدیجه (س) (۳ سال قبل از هجرت)" },
	{ holiday: false, month: 9, day: 15, base: "IR Islam", title: "ولادت امام حسن مجتبی (ع) (۳ ه‍.ق) و روز اکرام" },
	{ holiday: false, month: 9, day: 18, base: "IR Islam", title: "شب قدر" },
	{ holiday: false, month: 9, day: 19, base: "IR Islam", title: "ضربت خوردن امام علی (ع) (۴۰ ه‍.ق)" },
	{ holiday: false, month: 9, day: 20, base: "IR Islam", title: "شب قدر" },
	{ holiday: true, month: 9, day: 21, base: "IR Islam", title: "شهادت امام علی (ع) (۴۰ ه‍.ق)" },
	{ holiday: false, month: 9, day: 22, base: "IR Islam", title: "شب قدر" },
	{ holiday: true, month: 10, day: 1, base: "IR Islam", title: "عید سعید فطر" },
	{ holiday: true, month: 10, day: 2, base: "IR Islam", title: "تعطیل به مناسبت عید سعید فطر" },
	{ holiday: false, month: 10, day: 17, base: "IR Islam", title: "روز فرهنگ پهلوانی و ورزش زورخانه‌ای" },
	{ holiday: true, month: 10, day: 25, base: "IR Islam", title: "شهادت امام جعفر صادق (ع) (۱۴۸ ه‍.ق)" },
	{ holiday: false, month: 11, day: 1, base: "IR Islam", title: "ولادت حضرت معصومه (س) (۱۷۳ ه‍.ق) و روز دختر" },
	{ holiday: false, month: 11, day: 5, base: "IR Islam", title: "روز تجلیل از امام‌زادگان و بقاع متبرکه" },
	{ holiday: false, month: 11, day: 6, base: "IR Islam", title: "روز بزرگداشت حضرت احمدبن‌موسی شاهچراغ (ع)" },
	{ holiday: false, month: 11, day: 11, base: "IR Islam", title: "ولادت امام رضا (ع) (۱۴۸ ه‍.ق)" },
	{ holiday: false, month: 11, day: 30, base: "IR Islam", title: "شهادت امام محمد تقی (ع) (۲۲۰ ه‍.ق)" },
	{ holiday: false, month: 12, day: 1, base: "IR Islam", title: "سالروز ازدواج امام علی (ع) و حضرت فاطمه (س) (۲ ه‍.ق) – روز ازدواج" },
	{ holiday: false, month: 12, day: 6, base: "IR Islam", title: "شهادت زائران خانهٔ خدا به دست مأموران آل سعود (۱۳۶۶ ه‍.ش برابر با ۶ ذی‌الحجه ۱۴۰۷ ه‍.ق)" },
	{ holiday: false, month: 12, day: 7, base: "IR Islam", title: "شهادت امام محمد باقر (ع) (۱۱۴ ه‍.ق)" },
	{ holiday: false, month: 12, day: 9, base: "IR Islam", title: "روز عرفه (روز نیایش)" },
	{ holiday: true, month: 12, day: 10, base: "IR Islam", title: "عید سعید قربان (عید الاضحی)" },
	{ holiday: false, month: 12, day: 15, base: "IR Islam", title: "ولادت امام علی النقی الهادی (ع) (۲۱۲ ه‍.ق)" },
	{ holiday: true, month: 12, day: 18, base: "IR Islam", title: "عید سعید غدیر خم (۱۰ ه‍.ق)" },
	{ holiday: false, month: 12, day: 20, base: "IR Islam", title: "ولادت امام موسی کاظم (ع) (۱۲۸ ه‍.ق)" },
	{ holiday: false, month: 12, day: 24, base: "IR Islam", title: "روز مباهلهٔ پیامبر اسلام (ص) (۱۰ ه‍.ق)" },
	{ holiday: false, month: 12, day: 25, base: "IR Islam", title: "روز خانواده و تکریم بازنشستگان" },
	{ holiday: false, month: 2, day: 3, base: "IR Islam", title: "ولادت امام محمد باقر (ع) (۵۷ ﻫ.ق) به روایتی" },
	{ holiday: false, month: 3, day: 12, base: "IR Islam", title: "آغاز واجب شدن نماز، ورود پیامبر به مدینه" },
	{ holiday: false, month: 3, day: 15, base: "IR Islam", title: "بنای مسجد قبا (اولین مسجد در اسلام)" },
	{ holiday: false, month: 3, day: 16, base: "IR Islam", title: "ورود اهل بیت امام حسین (ع) به شام" },
	{ holiday: false, month: 3, day: 17, base: "IR Islam", title: "بنای مسجدالنبی در مدینه" },
	{ holiday: false, month: 3, day: 23, base: "IR Islam", title: "ورود حضرت معصومه (س) به قم" },
	{ holiday: false, month: 3, day: 26, base: "IR Islam", title: "صلح امام حسن (ع)" },
	{ holiday: false, month: 4, day: 3, base: "IR Islam", title: "سفر امام حسن (ع) به جرجان" },
	{ holiday: false, month: 4, day: 4, base: "IR Islam", title: "ولادت شاه عبدالعظیم حسنی (ع)" },
	{ holiday: false, month: 4, day: 8, base: "IR Islam", title: "شهادت حضرت فاطمهٔ زهرا (س) (۱۱ ﻫ.ق) به روایتی" },
	{ holiday: false, month: 5, day: 10, base: "IR Islam", title: "وقوع جنگ جمل بین سپاهیان امام علی (ع) و ناکثین" },
	{ holiday: false, month: 5, day: 27, base: "IR Islam", title: "وفات حضرت عبدالمطلب (ع)" },
	{ holiday: false, month: 6, day: 12, base: "IR Islam", title: "حرکت پیامبر به سمت خیبر" },
	{ holiday: false, month: 6, day: 19, base: "IR Islam", title: "ازدواج حضرت عبداللّه (ع) و آمنه (س)" },
	{ holiday: false, month: 6, day: 21, base: "IR Islam", title: "ولادت حضرت ام‌کلثوم (س)" },
	{ holiday: false, month: 7, day: 9, base: "IR Islam", title: "ولادت حضرت علی اصغر (ع)" },
	{ holiday: false, month: 7, day: 16, base: "IR Islam", title: "خروج فاطمه بنت اسد از کعبه" },
	{ holiday: false, month: 7, day: 23, base: "IR Islam", title: "مجروح شدن امام حسن مجتبی (ع) در ساباط مدائن" },
	{ holiday: false, month: 7, day: 23, base: "IR Islam", title: "مسموم شدن امام موسی کاظم (ع) به دستور مأمون" },
	{ holiday: false, month: 7, day: 24, base: "IR Islam", title: "فتح قلعهٔ خیبر توسط امام علی (ع)، بازگشت جعفر بن ابی‌طالب از حبشه" },
	{ holiday: false, month: 7, day: 26, base: "IR Islam", title: "وفات حضرت ابوطالب (ع)" },
	{ holiday: false, month: 7, day: 28, base: "IR Islam", title: "حرکت امام حسین (ع) از مدینه به مکه" },
	{ holiday: false, month: 7, day: 30, base: "IR Islam", title: "هجرت مسلمانان به حبشه، غزوهٔ نخله" },
	{ holiday: false, month: 8, day: 15, base: "IR Islam", title: "روز سربازان گمنام امام زمان (عج)" },
	{ holiday: false, month: 10, day: 21, base: "IR Islam", title: "فتح اندلس به دست مسلمانان (۹۲ ه‍.ق)" },
	{ holiday: false, month: 11, day: 5, base: "IR Islam", title: "روز بزرگداشت حضرت صالح بن موسی کاظم (ع)" }
] as const;
