import type { TEventObject } from "src/types";

const IR_GOVERNMENT_EVENTS: TEventObject[] = [
	{ holiday: true, month: 1, day: 1, base: "IR Government", title: "آغاز عید نوروز" },
	{ holiday: true, month: 1, day: 2, base: "IR Government", title: "عید نوروز" },
	{ holiday: false, month: 1, day: 2, base: "IR Government", title: "هجوم به مدرسهٔ فیضیهٔ قم (۱۳۴۲ ه‍.ش)" },
	{ holiday: false, month: 1, day: 2, base: "IR Government", title: "آغاز عملیات فتح‌المبین (۱۳۶۱ ه‍.ش)" },
	{ holiday: true, month: 1, day: 3, base: "IR Government", title: "عید نوروز" },
	{ holiday: true, month: 1, day: 4, base: "IR Government", title: "عید نوروز" },
	{ holiday: false, month: 1, day: 7, base: "IR Government", title: "روز هنرهای نمایشی" },
	{ holiday: true, month: 1, day: 12, base: "IR Government", title: "روز جمهوری اسلامی ایران" },
	{ holiday: true, month: 1, day: 13, base: "IR Government", title: "روز طبیعت" },
	{ holiday: false, month: 1, day: 18, base: "IR Government", title: "روز سلامتی" },
	{ holiday: false, month: 1, day: 20, base: "IR Government", title: "روز ملی فناوری هسته‌ای" },
	{ holiday: false, month: 1, day: 20, base: "IR Government", title: "روز هنر انقلاب اسلامی" },
	{ holiday: false, month: 1, day: 20, base: "IR Government", title: "شهادت سید مرتضی آوینی (۱۳۷۲ ه‍.ش)" },
	{ holiday: false, month: 1, day: 21, base: "IR Government", title: "شهادت امیر سپهبد علی صیاد شیرازی (۱۳۷۸ ه‍.ش)" },
	{ holiday: false, month: 1, day: 21, base: "IR Government", title: "سالروز افتتاح حساب شمارهٔ ۱۰۰ و تأسیس بنیاد مسکن انقلاب اسلامی (۱۳۵۸ ه‍.ش)" },
	{ holiday: false, month: 1, day: 25, base: "IR Government", title: "روز بزرگداشت عطار نیشابوری" },
	{ holiday: false, month: 1, day: 29, base: "IR Government", title: "روز ارتش جمهوری اسلامی و نیروی زمینی" },
	{ holiday: false, month: 2, day: 1, base: "IR Government", title: "روز بزرگداشت سعدی" },
	{ holiday: false, month: 2, day: 2, base: "IR Government", title: "تأسیس سپاه پاسداران انقلاب اسلامی (۱۳۵۸ ه‍.ش)" },
	{ holiday: false, month: 2, day: 2, base: "IR Government", title: "اعلام انقلاب فرهنگی (۱۳۵۹ ه‍.ش)" },
	{ holiday: false, month: 2, day: 3, base: "IR Government", title: "روز بزرگداشت شیخ بهایی" },
	{ holiday: false, month: 2, day: 5, base: "IR Government", title: "شکست حملهٔ نظامی آمریکا به ایران در طبس (۱۳۵۹ ه‍.ش)" },
	{ holiday: false, month: 2, day: 9, base: "IR Government", title: "روز شوراها" },
	{ holiday: false, month: 2, day: 10, base: "IR Government", title: "روز ملی خلیج فارس" },
	{ holiday: false, month: 2, day: 12, base: "IR Government", title: "شهادت استاد مرتضی مطهری (۱۳۵۸ ه‍.ش)" },
	{ holiday: false, month: 2, day: 12, base: "IR Government", title: "روز معلم" },
	{ holiday: false, month: 2, day: 15, base: "IR Government", title: "روز بزرگداشت شیخ صدوق" },
	{ holiday: false, month: 2, day: 18, base: "IR Government", title: "روز بیماری‌های خاص و صعب‌العلاج" },
	{ holiday: false, month: 2, day: 19, base: "IR Government", title: "روز بزرگداشت شیخ کلینی" },
	{ holiday: false, month: 2, day: 24, base: "IR Government", title: "لغو امتیاز تنباکو به فتوای آیت‌الله میرزا حسن شیرازی (۱۲۷۰ ه‍.ش)" },
	{ holiday: false, month: 2, day: 25, base: "IR Government", title: "روز پاسداشت زبان فارسی و بزرگداشت حکیم ابوالقاسم فردوسی" },
	{ holiday: false, month: 2, day: 28, base: "IR Government", title: "روز بزرگداشت حکیم عمر خیام" },
	{ holiday: false, month: 2, day: 30, base: "IR Government", title: "روز ملی جمعیت" },
	{ holiday: false, month: 2, day: 31, base: "IR Government", title: "روز اهدای عضو، اهدای زندگی" },
	{ holiday: false, month: 3, day: 1, base: "IR Government", title: "روز بهره‌وری و بهینه‌سازی مصرف" },
	{ holiday: false, month: 3, day: 1, base: "IR Government", title: "روز بزرگداشت ملاصدرا (صدرالمتألهین)" },
	{ holiday: false, month: 3, day: 3, base: "IR Government", title: "فتح خرمشهر در عملیات بیت‌المقدس (۱۳۶۱ ه‍.ش) و روز مقاومت، ایثار و پیروزی" },
	{ holiday: false, month: 3, day: 4, base: "IR Government", title: "روز دزفول" },
	{ holiday: false, month: 3, day: 4, base: "IR Government", title: " روز مقاومت و پایداری" },
	{ holiday: true, month: 3, day: 14, base: "IR Government", title: "رحلت امام خمینی رهبر انقلاب اسلامی (۱۳۶۸ ه‍.ش)" },
	{ holiday: false, month: 3, day: 14, base: "IR Government", title: "انتخاب آیت‌الله خامنه‌ای به رهبری (۱۳۶۸ ه‍.ش)" },
	{ holiday: true, month: 3, day: 15, base: "IR Government", title: "قیام خونین ۱۵ خرداد (۱۳۴۲ ه‍.ش)" },
	{ holiday: false, month: 3, day: 26, base: "IR Government", title: "شهادت بخارایی، امانی، صفار هرندی و نیک‌نژاد از اعضای فدائیان اسلام (۱۳۴۴ ه‍.ش)" },
	{ holiday: false, month: 3, day: 27, base: "IR Government", title: "روز جهاد کشاورزی (تشکیل جهاد سازندگی، ۱۳۵۸ ه‍.ش)" },
	{ holiday: false, month: 3, day: 29, base: "IR Government", title: "درگذشت دکتر علی شریعتی (۱۳۵۶ ه‍.ش)" },
	{ holiday: false, month: 3, day: 31, base: "IR Government", title: "شهادت دکتر مصطفی چمران (۱۳۶۰ ه‍.ش)" },
	{ holiday: false, month: 3, day: 31, base: "IR Government", title: "روز بسیج استادان" },
	{ holiday: false, month: 4, day: 1, base: "IR Government", title: "روز تبلیغ و اطلاع‌رسانی دینی (تأسیس سازمان تبلیغات اسلامی ۱۳۶۰ ه‍.ش)" },
	{ holiday: false, month: 4, day: 1, base: "IR Government", title: "روز اصناف" },
	{ holiday: false, month: 4, day: 7, base: "IR Government", title: "شهادت آیت‌الله دکتر بهشتی و ۷۲ تن از یاران (۱۳۶۰ ه‍.ش)" },
	{ holiday: false, month: 4, day: 7, base: "IR Government", title: "روز قوهٔ قضاییه" },
	{ holiday: false, month: 4, day: 8, base: "IR Government", title: "روز مبارزه با سلاح‌های شیمیایی و میکروبی" },
	{ holiday: false, month: 4, day: 10, base: "IR Government", title: "روز صنعت و معدن" },
	{ holiday: false, month: 4, day: 11, base: "IR Government", title: "شهادت آیت‌الله صدوقی (۱۳۶۱ ه‍.ش)" },
	{ holiday: false, month: 4, day: 12, base: "IR Government", title: "حملهٔ ناوگان آمریکا به هواپیمای مسافربری ایران (۱۳۶۷ ه‍.ش)" },
	{ holiday: false, month: 4, day: 12, base: "IR Government", title: "روز افشای حقوق بشر آمریکایی" },
	{ holiday: false, month: 4, day: 14, base: "IR Government", title: "روز شهرداری و دهیاری" },
	{ holiday: false, month: 4, day: 14, base: "IR Government", title: "روز قلم" },
	{ holiday: false, month: 4, day: 18, base: "IR Government", title: "روز ادبیات کودکان و نوجوانان" },
	{ holiday: false, month: 4, day: 21, base: "IR Government", title: "روز عفاف و حجاب" },
	{ holiday: false, month: 4, day: 23, base: "IR Government", title: "روز گفت‌وگو و تعامل سازنده با جهان" },
	{ holiday: false, month: 4, day: 25, base: "IR Government", title: "روز بهزیستی و تامین اجتماعی" },
	{ holiday: false, month: 4, day: 26, base: "IR Government", title: "سالروز تأسیس نهاد شورای نگهبان" },
	{ holiday: false, month: 5, day: 5, base: "IR Government", title: "سالروز عملیات مرصاد (۱۳۶۷ ه‍.ش)" },
	{ holiday: false, month: 5, day: 9, base: "IR Government", title: "روز اهدای خون" },
	{ holiday: false, month: 5, day: 14, base: "IR Government", title: "صدور فرمان مشروطیت (۱۲۸۵ ه‍.ش)" },
	{ holiday: false, month: 5, day: 14, base: "IR Government", title: "روز حقوق بشر اسلامی و کرامت انسانی" },
	{ holiday: false, month: 5, day: 16, base: "IR Government", title: "تشکیل جهاد دانشگاهی (۱۳۵۹ ه‍.ش)" },
	{ holiday: false, month: 5, day: 17, base: "IR Government", title: "روز خبرنگار" },
	{ holiday: false, month: 5, day: 21, base: "IR Government", title: "روز حمایت از صنایع کوچک" },
	{ holiday: false, month: 5, day: 22, base: "IR Government", title: "روز تشکل‌ها و مشارکت‌های اجتماعی" },
	{ holiday: false, month: 5, day: 23, base: "IR Government", title: "روز مقاومت اسلامی" },
	{ holiday: false, month: 5, day: 26, base: "IR Government", title: "آغاز بازگشت آزادگان به ایران (۱۳۶۹ ه‍.ش)" },
	{ holiday: false, month: 5, day: 28, base: "IR Government", title: "کودتای ۲۸ مرداد (۱۳۳۲ ه‍.ش)" },
	{ holiday: false, month: 5, day: 28, base: "IR Government", title: "آتش‌سوزی سینما رکس آبادان (۱۳۵۷ ه‍.ش)" },
	{ holiday: false, month: 5, day: 30, base: "IR Government", title: "روز بزرگداشت علامه مجلسی" },
	{ holiday: false, month: 6, day: 1, base: "IR Government", title: "روز بزرگداشت ابوعلی سینا" },
	{ holiday: false, month: 6, day: 1, base: "IR Government", title: "روز پزشک" },
	{ holiday: false, month: 6, day: 2, base: "IR Government", title: "آغاز هفتهٔ دولت" },
	{ holiday: false, month: 6, day: 2, base: "IR Government", title: "شهادت سید علی اندرزگو (۱۳۵۷ ه‍.ش)" },
	{ holiday: false, month: 6, day: 4, base: "IR Government", title: "روز کارمند" },
	{ holiday: false, month: 6, day: 5, base: "IR Government", title: "روز بزرگداشت محمد بن زکریای رازی" },
	{ holiday: false, month: 6, day: 5, base: "IR Government", title: "روز داروسازی" },
	{ holiday: false, month: 6, day: 5, base: "IR Government", title: "روز کشتی" },
	{ holiday: false, month: 6, day: 8, base: "IR Government", title: "روز مبارزه با تروریسم (انفجار دفتر نخست‌وزیری و شهادت رجایی و باهنر - ۱۳۶۰ ه‍.ش)" },
	{ holiday: false, month: 6, day: 12, base: "IR Government", title: "روز مبارزه با استعمار انگلیس (سالروز شهادت رئیس‌علی دلواری)" },
	{ holiday: false, month: 6, day: 13, base: "IR Government", title: "روز تعاون" },
	{ holiday: false, month: 6, day: 13, base: "IR Government", title: "روز بزرگداشت ابوریحان بیرونی" },
	{ holiday: false, month: 6, day: 14, base: "IR Government", title: "شهادت آیت‌الله قدوسی و سرتیپ وحید دستجردی (۱۳۶۰ ه‍.ش)" },
	{ holiday: false, month: 6, day: 17, base: "IR Government", title: "قیام ۱۷ شهریور و کشتار جمعی از مردم به دست مأموران پهلوی (۱۳۵۷ ه‍.ش)" },
	{ holiday: false, month: 6, day: 19, base: "IR Government", title: "وفات آیت‌الله سید محمود طالقانی اولین امام جمعهٔ تهران (۱۳۵۸ ه‍.ش)" },
	{ holiday: false, month: 6, day: 20, base: "IR Government", title: "شهادت آیت‌الله مدنی (۱۳۶۰ ه‍.ش)" },
	{ holiday: false, month: 6, day: 21, base: "IR Government", title: "روز سینما" },
	{ holiday: false, month: 6, day: 27, base: "IR Government", title: "روز شعر و ادب فارسی" },
	{ holiday: false, month: 6, day: 27, base: "IR Government", title: "روز بزرگداشت استاد سید محمدحسین شهریار" },
	{ holiday: false, month: 6, day: 31, base: "IR Government", title: "آغاز جنگ تحمیلی (۱۳۵۹ ه‍.ش)" },
	{ holiday: false, month: 6, day: 31, base: "IR Government", title: "آغاز هفتهٔ دفاع مقدس" },
	{ holiday: false, month: 7, day: 5, base: "IR Government", title: "شکست حصر آبادان در عملیات ثامن‌الأئمه (ع) (۱۳۶۰ ه‍.ش)" },
	{ holiday: false, month: 7, day: 7, base: "IR Government", title: "روز بزرگداشت فرماندهان شهید دفاع مقدس" },
	{ holiday: false, month: 7, day: 7, base: "IR Government", title: "شهادت فلاحی، فکوری، نامجو، کلاهدوز و جهان‌آرا از فرماندهان ارتش و سپاه (۱۳۶۰ ه‍.ش)" },
	{ holiday: false, month: 7, day: 7, base: "IR Government", title: "روز آتش‌نشانی و ایمنی" },
	{ holiday: false, month: 7, day: 7, base: "IR Government", title: "روز بزرگداشت شمس" },
	{ holiday: false, month: 7, day: 8, base: "IR Government", title: "روز بزرگداشت مولوی" },
	{ holiday: false, month: 7, day: 9, base: "IR Government", title: "روز همبستگی و همدردی با کودکان و نوجوانان فلسطینی" },
	{ holiday: false, month: 7, day: 13, base: "IR Government", title: "هجرت امام خمینی از عراق به پاریس (۱۳۵۷ ه‍.ش)" },
	{ holiday: false, month: 7, day: 13, base: "IR Government", title: "روز نیروی انتظامی" },
	{ holiday: false, month: 7, day: 14, base: "IR Government", title: "روز دامپزشکی" },
	{ holiday: false, month: 7, day: 15, base: "IR Government", title: "روز روستا و عشایر" },
	{ holiday: false, month: 7, day: 20, base: "IR Government", title: "روز بزرگداشت حافظ" },
	{ holiday: false, month: 7, day: 23, base: "IR Government", title: "شهادت آیت‌الله اشرفی اصفهانی (۱۳۶۱ ه‍.ش)" },
	{ holiday: false, month: 7, day: 24, base: "IR Government", title: "روز ملی پارالمپیک" },
	{ holiday: false, month: 7, day: 26, base: "IR Government", title: "روز تربیت بدنی و ورزش" },
	{ holiday: false, month: 8, day: 4, base: "IR Government", title: "اعتراض امام خمینی علیه پذیرش کاپیتولاسیون (۱۳۴۳ ه‍.ش)" },
	{ holiday: false, month: 8, day: 8, base: "IR Government", title: "شهادت محمد حسین فهمیده (بسیجی ۱۳ ساله)" },
	{ holiday: false, month: 8, day: 8, base: "IR Government", title: "روز نوجوان و بسیج دانش‌آموزی" },
	{ holiday: false, month: 8, day: 10, base: "IR Government", title: "شهادت آیت‌الله قاضی طباطبایی (۱۳۵۸ ه‍.ش)" },
	{ holiday: false, month: 8, day: 13, base: "IR Government", title: "تسخیر سفارت آمریکا (۱۳۵۸ ه‍.ش)" },
	{ holiday: false, month: 8, day: 13, base: "IR Government", title: "روز ملی مبارزه با استکبار جهانی" },
	{ holiday: false, month: 8, day: 13, base: "IR Government", title: "روز دانش‌آموز" },
	{ holiday: false, month: 8, day: 14, base: "IR Government", title: "روز فرهنگ عمومی" },
	{ holiday: false, month: 8, day: 24, base: "IR Government", title: "روز کتاب، کتابخوانی و کتابدار" },
	{ holiday: false, month: 8, day: 24, base: "IR Government", title: "روز بزرگداشت آیت‌الله علامه سید محمد حسین طباطبایی (۱۳۶۰ ه‍.ش)" },
	{ holiday: false, month: 9, day: 5, base: "IR Government", title: "سالروز قیام مردم گرگان (۱۳۵۷ ه‍.ش)" },
	{ holiday: false, month: 9, day: 5, base: "IR Government", title: "تشکیل بسیج مستضعفان (۱۳۵۸ ه‍.ش)" },
	{ holiday: false, month: 9, day: 7, base: "IR Government", title: "روز نیروی دریایی" },
	{ holiday: false, month: 9, day: 9, base: "IR Government", title: "روز بزرگداشت شیخ مفید" },
	{ holiday: false, month: 9, day: 10, base: "IR Government", title: "شهادت آیت‌الله سید حسن مدرس (۱۳۱۶ ه‍.ش)" },
	{ holiday: false, month: 9, day: 10, base: "IR Government", title: "روز مجلس" },
	{ holiday: false, month: 9, day: 12, base: "IR Government", title: "روز قانون اساسی جمهوری اسلامی ایران (تصویب قانون اساسی جمهوری اسلامی ایران - ۱۳۵۸ ه‍.ش)" },
	{ holiday: false, month: 9, day: 16, base: "IR Government", title: "روز دانشجو" },
	{ holiday: false, month: 9, day: 19, base: "IR Government", title: "تشکیل شورای عالی انقلاب فرهنگی (۱۳۶۳ ه‍.ش)" },
	{ holiday: false, month: 9, day: 20, base: "IR Government", title: "شهادت آیت‌الله دستغیب (۱۳۶۰ ه‍.ش)" },
	{ holiday: false, month: 9, day: 25, base: "IR Government", title: "روز پژوهش" },
	{ holiday: false, month: 9, day: 27, base: "IR Government", title: "شهادت آیت‌الله دکتر محمد مفتح (۱۳۵۸ ه‍.ش)" },
	{ holiday: false, month: 9, day: 27, base: "IR Government", title: "روز وحدت حوزه و دانشگاه" },
	{ holiday: false, month: 9, day: 30, base: "IR Government", title: "شب یلدا (چله)" },
	{ holiday: false, month: 10, day: 5, base: "IR Government", title: "روز ایمنی در برابر زلزله و کاهش اثرات بلایای طبیعی" },
	{ holiday: false, month: 10, day: 7, base: "IR Government", title: "تشکیل نهضت سوادآموزی (۱۳۵۸ ه‍.ش)" },
	{ holiday: false, month: 10, day: 19, base: "IR Government", title: "قیام خونین مردم قم (۱۳۵۶ ه‍.ش)" },
	{ holiday: false, month: 10, day: 20, base: "IR Government", title: "شهادت میرزاتقی‌خان امیرکبیر (۱۲۳۰ ه‍.ش)" },
	{ holiday: false, month: 10, day: 22, base: "IR Government", title: "تشکیل شورای انقلاب (۱۳۵۷ ه‍.ش)" },
	{ holiday: false, month: 10, day: 26, base: "IR Government", title: "خروج شاه از ایران (۱۳۵۷ ه‍.ش)" },
	{ holiday: false, month: 10, day: 27, base: "IR Government", title: "شهادت نواب صفوی، طهماسبی، برادران واحدی و ذوالقدر از اعضای فداییان اسلام (۱۳۳۴ ه‍.ش)" },
	{ holiday: false, month: 10, day: 29, base: "IR Government", title: "روز غزه" },
	{ holiday: false, month: 11, day: 6, base: "IR Government", title: "سالروز حماسهٔ مردم آمل" },
	{ holiday: false, month: 11, day: 12, base: "IR Government", title: "بازگشت امام خمینی به ایران (۱۳۵۷ ه‍.ش) و آغاز دههٔ فجر انقلاب اسلامی" },
	{ holiday: false, month: 11, day: 14, base: "IR Government", title: "روز فناوری فضایی" },
	{ holiday: false, month: 11, day: 19, base: "IR Government", title: "روز نیروی هوایی" },
	{ holiday: true, month: 11, day: 22, base: "IR Government", title: "پیروزی انقلاب اسلامی ایران و سقوط نظام شاهنشاهی (۱۳۵۷ ه‍.ش)" },
	{ holiday: false, month: 11, day: 29, base: "IR Government", title: "قیام مردم تبریز به مناسبت چهلمین روز شهادت شهدای قم (۱۳۵۶ ه‍.ش)" },
	{ holiday: false, month: 11, day: 29, base: "IR Government", title: "روز اقتصاد مقاومتی و کارآفرینی" },
	{ holiday: false, month: 12, day: 5, base: "IR Government", title: "روز بزرگداشت خواجه نصیرالدین طوسی" },
	{ holiday: false, month: 12, day: 5, base: "IR Government", title: "روز مهندسی" },
	{ holiday: false, month: 12, day: 14, base: "IR Government", title: "روز احسان و نیکوکاری" },
	{ holiday: false, month: 12, day: 15, base: "IR Government", title: "روز درختکاری" },
	{ holiday: false, month: 12, day: 18, base: "IR Government", title: "روز بزرگداشت سید جمال‌الدین اسدآبادی" },
	{ holiday: false, month: 12, day: 18, base: "IR Government", title: "سالروز تأسیس کانون‌های فرهنگی و هنری مساجد کشور" },
	{ holiday: false, month: 12, day: 20, base: "IR Government", title: "روز راهیان نور" },
	{ holiday: false, month: 12, day: 21, base: "IR Government", title: "روز بزرگداشت نظامی گنجوی" },
	{ holiday: false, month: 12, day: 22, base: "IR Government", title: "روز بزرگداشت شهدا (تأسیس بنیاد شهید انقلاب اسلامی - ۱۳۵۸ ه‍.ش)" },
	{ holiday: false, month: 12, day: 25, base: "IR Government", title: "روز بزرگداشت پروین اعتصامی" },
	{ holiday: true, month: 12, day: 29, base: "IR Government", title: "روز ملی شدن صنعت نفت ایران (۱۳۲۹ ه‍.ش)" },
	{ holiday: false, month: 1, day: 10, base: "IR Government", title: "همه‌پرسی تغییر نظام شاهنشاهی به جمهوری اسلامی ایران (۱۳۵۸ ه‍.ش)" },
	{ holiday: false, month: 1, day: 15, base: "IR Government", title: "روز ذخایر ژنتیکی و زیستی" },
	{ holiday: false, month: 1, day: 19, base: "IR Government", title: "شهادت آیت‌الله سید محمد باقر صدر و خواهرشان بنت‌الهدی (۱۳۵۹ ه‍.ش)" },
	{ holiday: false, month: 1, day: 20, base: "IR Government", title: "قطع مناسبات سیاسی ایران و آمریکا (۱۳۵۹ ه‍.ش)" },
	{ holiday: false, month: 2, day: 2, base: "IR Government", title: "روز زمین پاک" },
	{ holiday: false, month: 2, day: 7, base: "IR Government", title: "روز ایمنی حمل‌ونقل" },
	{ holiday: false, month: 2, day: 10, base: "IR Government", title: "آغاز عملیات بیت المقدس (۱۳۶۱ ه‍.ش)" },
	{ holiday: false, month: 2, day: 11, base: "IR Government", title: "روز جهانی کارگر (۱ مه)" },
	{ holiday: false, month: 2, day: 19, base: "IR Government", title: "روز اسناد ملی و میراث مکتوب" },
	{ holiday: false, month: 3, day: 5, base: "IR Government", title: "روز نسیم مهر (روز حمایت از خانوادهٔ زندانیان)" },
	{ holiday: false, month: 3, day: 7, base: "IR Government", title: "افتتاح اولین دورهٔ مجلس شورای اسلامی (۱۳۵۹ ه‍.ش)" },
	{ holiday: false, month: 3, day: 15, base: "IR Government", title: "زندانی شدن امام خمینی (۱۳۴۲ ه‍.ش)" },
	{ holiday: false, month: 3, day: 20, base: "IR Government", title: "شهادت آیت‌الله سعیدی (۱۳۴۹ ه‍.ش)" },
	{ holiday: false, month: 3, day: 25, base: "IR Government", title: "روز گل و گیاه" },
	{ holiday: false, month: 3, day: 30, base: "IR Government", title: "شهادت زائران حرم رضوی (ع) (عاشورای ۱۳۷۳ ه‍.ش)" },
	{ holiday: false, month: 4, day: 10, base: "IR Government", title: "روز آزادسازی شهر مهران" },
	{ holiday: false, month: 4, day: 12, base: "IR Government", title: "روز بزرگداشت علامه امینی (۱۳۴۹ ه‍.ش)" },
	{ holiday: false, month: 4, day: 16, base: "IR Government", title: "روز مالیات" },
	{ holiday: false, month: 4, day: 21, base: "IR Government", title: "کشف توطئهٔ کودتا در پایگاه هوایی شهید نوژه (۱۳۵۹ ه‍.ش)" },
	{ holiday: false, month: 4, day: 18, base: "IR Government", title: "کشف کودتای نوژه (۱۳۵۹ ه‍.ش)" },
	{ holiday: false, month: 4, day: 21, base: "IR Government", title: "حمله به مسجد گوهرشاد و کشتار مردم (۱۳۱۴ ه‍.ش)" },
	{ holiday: false, month: 4, day: 23, base: "IR Government", title: "گشایش نخستین مجلس خبرگان رهبری (۱۳۶۲ ه‍.ش)" },
	{ holiday: false, month: 4, day: 27, base: "IR Government", title: "اعلام پذیرش قطعنامهٔ ۵۹۸ شورای امنیت از سوی ایران (۱۳۶۷ ه‍.ش)" },
	{ holiday: false, month: 4, day: 30, base: "IR Government", title: "روز بزرگداشت آیت‌الله سیدابوالقاسم کاشانی" },
	{ holiday: false, month: 5, day: 6, base: "IR Government", title: "روز کارآفرینی و آموزش‌های فنی و حرفه‌ای" },
	{ holiday: false, month: 5, day: 8, base: "IR Government", title: "روز بزرگداشت شیخ شهاب‌الدین سهروردی (شیخ اشراق)" },
	{ holiday: false, month: 5, day: 11, base: "IR Government", title: "شهادت آیت‌الله شیخ فضل‌الله نوری (۱۲۸۸ ه‍.ش)" },
	{ holiday: false, month: 5, day: 28, base: "IR Government", title: "گشایش مجلس خبرگان برای بررسی نهایی قانون اساسی جمهوری اسلامی ایران (۱۳۵۸ ه‍.ش)" },
	{ holiday: false, month: 5, day: 31, base: "IR Government", title: "روز صنعت دفاعی" },
	{ holiday: false, month: 6, day: 3, base: "IR Government", title: "اشغال ایران به دست متفقین (۱۳۲۰ ه‍.ش)" },
	{ holiday: false, month: 6, day: 10, base: "IR Government", title: "تصویب قانون عملیات بانکی بدون ربا (۱۳۶۲ ه‍.ش)" },
	{ holiday: false, month: 6, day: 10, base: "IR Government", title: "روز بانکداری اسلامی" },
	{ holiday: false, month: 6, day: 11, base: "IR Government", title: "روز صنعت چاپ" },
	{ holiday: false, month: 6, day: 12, base: "IR Government", title: "روز بهورز" },
	{ holiday: false, month: 6, day: 13, base: "IR Government", title: "روز مردم‌شناسی" },
	{ holiday: false, month: 6, day: 30, base: "IR Government", title: "روز گفت‌وگوی تمدن‌ها" },
	{ holiday: false, month: 7, day: 20, base: "IR Government", title: "روز اسکان معلولان و سالمندان" },
	{ holiday: false, month: 7, day: 24, base: "IR Government", title: "روز پیوند اولیا و مربیان" },
	{ holiday: false, month: 7, day: 24, base: "IR Government", title: "به آتش کشیده‌شدن مسجد جامع شهر کرمان (۱۳۵۷ ه‍.ش)" },
	{ holiday: false, month: 7, day: 29, base: "IR Government", title: "روز صادرات" },
	{ holiday: false, month: 8, day: 1, base: "IR Government", title: "شهادت آیت‌الله حاج سید مصطفی خمینی (۱۳۵۶ ه‍.ش)" },
	{ holiday: false, month: 8, day: 1, base: "IR Government", title: "روز آمار و برنامه‌ریزی" },
	{ holiday: false, month: 8, day: 8, base: "IR Government", title: "روز پدافند غیرعامل" },
	{ holiday: false, month: 8, day: 13, base: "IR Government", title: "تبعید امام خمینی از ایران به ترکیه (۱۳۴۳ ه‍.ش)" },
	{ holiday: false, month: 8, day: 18, base: "IR Government", title: "روز کیفیت" },
	{ holiday: false, month: 8, day: 26, base: "IR Government", title: "آزادسازی سوسنگرد" },
	{ holiday: false, month: 9, day: 11, base: "IR Government", title: "شهادت میرزا کوچک خان جنگلی (۱۳۰۰ ه‍.ش)" },
	{ holiday: false, month: 9, day: 13, base: "IR Government", title: "روز بیمه" },
	{ holiday: false, month: 9, day: 18, base: "IR Government", title: "معرفی عراق به عنوان مسئول و آغازگر جنگ از سوی سازمان ملل (۱۳۷۰ ه‍.ش)" },
	{ holiday: false, month: 9, day: 26, base: "IR Government", title: "روز حمل و نقل و رانندگان" },
	{ holiday: false, month: 9, day: 29, base: "IR Government", title: "روز تجلیل از شهید تندگویان" },
	{ holiday: false, month: 10, day: 3, base: "IR Government", title: "روز ثبت احوال" },
	{ holiday: false, month: 10, day: 7, base: "IR Government", title: "شهادت آیت‌الله حسین غفاری (۱۳۵۳ ه‍.ش)" },
	{ holiday: false, month: 10, day: 8, base: "IR Government", title: "روز صنعت پتروشیمی" },
	{ holiday: false, month: 10, day: 9, base: "IR Government", title: "۹ دی" },
	{ holiday: false, month: 10, day: 13, base: "IR Government", title: "ابلاغ پیام تاریخی امام خمینی به گورباچف رهبر شوروی سابق (۱۳۶۷ ه‍.ش)" },
	{ holiday: false, month: 10, day: 17, base: "IR Government", title: "اجرای طرح حذف حجاب (۱۳۱۴ ه‍.ش)" },
	{ holiday: false, month: 11, day: 5, base: "IR Government", title: "انتخابات اولین دورهٔ ریاست جمهوری (۱۳۵۸ ه‍.ش)" },
	{ holiday: false, month: 11, day: 21, base: "IR Government", title: "شکسته شدن حکومت نظامی به فرمان امام خمینی (۱۳۵۷ ه‍.ش)" },
	{ holiday: false, month: 11, day: 25, base: "IR Government", title: "صدور حکم امام خمینی مبنی بر ارتداد سلمان رشدی (۱۳۶۷ ه‍.ش)" },
	{ holiday: false, month: 12, day: 3, base: "IR Government", title: "کودتای رضاخان (۱۲۹۹ ه‍.ش)" },
	{ holiday: false, month: 12, day: 8, base: "IR Government", title: "روز امور تربیتی و تربیت اسلامی" },
	{ holiday: false, month: 12, day: 9, base: "IR Government", title: "روز ملی حمایت از حقوق مصرف‌کنندگان" },
	{ holiday: false, month: 12, day: 24, base: "IR Government", title: "برگزاری انتخابات اولین دورهٔ مجلس شورای اسلامی (۱۳۵۸ ه‍.ش)" },
	{ holiday: false, month: 12, day: 25, base: "IR Government", title: "بمباران شیمیایی حلبچه توسط ارتش بعث عراق (۱۳۶۶ ه‍.ش)" },
]

const IR_ANCIENT_EVENTS: TEventObject[] = [
	{ holiday: false, month: 1, day: 6, base: "IR Ancient", title: "روز امید، روز شادباش‌نویسی" },
	{ holiday: false, month: 1, day: 10, base: "IR Ancient", title: "جشن آبانگاه" },
	{ holiday: false, month: 1, day: 13, base: "IR Ancient", title: "جشن سیزده‌بدر" },
	{ holiday: false, month: 1, day: 17, base: "IR Ancient", title: "سروش‌روز، جشن سروشگان" },
	{ holiday: false, month: 1, day: 19, base: "IR Ancient", title: "فرورین‌روز، جشن فروردینگان" },
	{ holiday: false, month: 2, day: 2, base: "IR Ancient", title: "جشن گیاه‌آوری" },
	{ holiday: false, month: 2, day: 3, base: "IR Ancient", title: "اردیبهشت‌روز، جشن اردیبهشتگان" },
	{ holiday: false, month: 2, day: 10, base: "IR Ancient", title: "جشن چهلم نوروز" },
	{ holiday: false, month: 2, day: 15, base: "IR Ancient", title: "گاهنبار میدیوزَرِم، جشن میانهٔ بهار، جشن بهاربُد / روز پیام‌آوری زرتشت" },
	{ holiday: false, month: 3, day: 1, base: "IR Ancient", title: "ارغاسوان، جشن گرما" },
	{ holiday: false, month: 3, day: 6, base: "IR Ancient", title: "خردادروز، جشن خردادگان" },
	{ holiday: false, month: 4, day: 1, base: "IR Ancient", title: "جشن آب‌پاشونک، جشن آغاز تابستان / سال نو در گاهشماری گاهنباری / دیدار طلوع خورشید در تقویم آفتابی چارتاقی نیاسر" },
	{ holiday: false, month: 4, day: 6, base: "IR Ancient", title: "جشن نیلوفر" },
	{ holiday: false, month: 4, day: 13, base: "IR Ancient", title: "تیرروز، جشن تیرگان" },
	{ holiday: false, month: 4, day: 15, base: "IR Ancient", title: "جشن خام‌خواری" },
	{ holiday: false, month: 5, day: 7, base: "IR Ancient", title: "مردادروز، جشن مردادگان" },
	{ holiday: false, month: 5, day: 10, base: "IR Ancient", title: "جشن چلهٔ تابستان" },
	{ holiday: false, month: 5, day: 15, base: "IR Ancient", title: "گاهنبار میدیوشِم، جشن میانهٔ تابستان" },
	{ holiday: false, month: 5, day: 18, base: "IR Ancient", title: "جشن مَی‌خواره" },
	{ holiday: false, month: 6, day: 1, base: "IR Ancient", title: "فغدیه، جشن خنکی هوا" },
	{ holiday: false, month: 6, day: 3, base: "IR Ancient", title: "جشن کشمین" },
	{ holiday: false, month: 6, day: 4, base: "IR Ancient", title: "شهریورروز، جشن شهریورگان / زادروز داراب (کوروش) / عروج مانی" },
	{ holiday: false, month: 6, day: 8, base: "IR Ancient", title: "خزان‌جشن" },
	{ holiday: false, month: 6, day: 15, base: "IR Ancient", title: "بازارجشن" },
	{ holiday: false, month: 6, day: 31, base: "IR Ancient", title: "گاهنبار پَتیَه‌شَهیم، جشن پایان تابستان" },
	{ holiday: false, month: 7, day: 1, base: "IR Ancient", title: "جشن میتراکانا / سال نو هخامنشی" },
	{ holiday: false, month: 7, day: 12, base: "IR Ancient", title: "آیین قالیشویان اردهال، بازماندی از تیرگان" },
	{ holiday: false, month: 7, day: 13, base: "IR Ancient", title: "تیرروز، جشن تیرروزی" },
	{ holiday: false, month: 7, day: 16, base: "IR Ancient", title: "مهرروز، جشن مهرگان" },
	{ holiday: false, month: 7, day: 21, base: "IR Ancient", title: "رام‌روز، جشن رام‌روزی / جشن پیروزی کاوه و فریدون" },
	{ holiday: false, month: 8, day: 7, base: "IR Ancient", title: " روز کوروش بزرگ" },
	{ holiday: false, month: 8, day: 10, base: "IR Ancient", title: "آبان‌روز، جشن آبانگان" },
	{ holiday: false, month: 8, day: 15, base: "IR Ancient", title: "گاهنبار اَیاثرَم، جشن میانهٔ پاییز" },
	{ holiday: false, month: 9, day: 1, base: "IR Ancient", title: "آذرجشن" },
	{ holiday: false, month: 9, day: 9, base: "IR Ancient", title: "آذرروز، جشن آذرگان" },
	{ holiday: false, month: 9, day: 30, base: "IR Ancient", title: "گاهنبار میدیارِم، جشن میانهٔ سال گاهنباری (از مبدأ آغاز تابستان)" },
	{ holiday: false, month: 10, day: 1, base: "IR Ancient", title: "روز میلاد خورشید، جشن خرم‌روز / نخستین جشن دیگان / دیدار طلوع خورشید در تقویم آفتابی چارتاقی نیاسر" },
	{ holiday: false, month: 10, day: 5, base: "IR Ancient", title: "بازارجشن" },
	{ holiday: false, month: 10, day: 8, base: "IR Ancient", title: "دی‌به‌آذرروز، دومین جشن دیگان" },
	{ holiday: false, month: 10, day: 14, base: "IR Ancient", title: "سیرسور، جشن گیاه‌خواری" },
	{ holiday: false, month: 10, day: 15, base: "IR Ancient", title: "جشن پیکرتراشی / دی‌به‌مهرروز، سومین جشن دیگان" },
	{ holiday: false, month: 10, day: 16, base: "IR Ancient", title: "جشن درامزینان، جشن درفش‌ها" },
	{ holiday: false, month: 10, day: 23, base: "IR Ancient", title: "دی‌به‌دین‌روز، چهارمین جشن دیگان" },
	{ holiday: false, month: 11, day: 1, base: "IR Ancient", title: "زادروز فردوسی" },
	{ holiday: false, month: 11, day: 2, base: "IR Ancient", title: "بهمن‌روز، جشن بهمنگان" },
	{ holiday: false, month: 11, day: 4, base: "IR Ancient", title: "شهریورروز، آغاز پادشاهی داراب (کوروش)" },
	{ holiday: false, month: 11, day: 5, base: "IR Ancient", title: "جشن نوسَره" },
	{ holiday: false, month: 11, day: 10, base: "IR Ancient", title: "آبان‌روز، جشن سَدَه، آتش‌افروزی بر بام‌ها / نمایش‌بازی همگانی" },
	{ holiday: false, month: 11, day: 15, base: "IR Ancient", title: "جشن میانهٔ زمستان" },
	{ holiday: false, month: 11, day: 22, base: "IR Ancient", title: "بادروز، جشن بادروزی" },
	{ holiday: false, month: 12, day: 1, base: "IR Ancient", title: "جشن اسفندی / جشن آبسالان، بهارجشن / نمایش‌بازی همگانی" },
	{ holiday: false, month: 12, day: 5, base: "IR Ancient", title: "اسفندروز، جشن اسفندگان، گرامیداشت زمین و بانوان / جشن برزگران" },
	{ holiday: false, month: 12, day: 10, base: "IR Ancient", title: "جشن وخشنکام" },
	{ holiday: false, month: 12, day: 19, base: "IR Ancient", title: "جشن نوروز رودها" },
	{ holiday: false, month: 12, day: 20, base: "IR Ancient", title: "جشن گلدان" },
	{ holiday: false, month: 12, day: 25, base: "IR Ancient", title: "هزارهٔ شاهنامه، هزارمین سالگرد پایان سرایش شاهنامهٔ فردوسی" },
	{ holiday: false, month: 12, day: 26, base: "IR Ancient", title: "فروردگان" },
	{ holiday: false, month: 12, day: 29, base: "IR Ancient", title: "گاهنبار هَمَسپَتمَدَم، جشن پایان زمستان (در آخرین روز سال) / جشن اوشیدر (نجات‌بخش ایرانی) در دریاچهٔ هامون و کوه خواجه / آتش‌افروزی بر بام‌ها در استقبال از نوروز" },
	{ holiday: false, month: 1, day: 6, base: "IR Ancient", title: "روز تولد زرتشت" },
	{ holiday: false, month: 10, day: 5, base: "IR Ancient", title: "روز درگذشت زرتشت" },
]

export const JALALI_EVENTS: TEventObject[] = [
	...IR_GOVERNMENT_EVENTS,
	...IR_ANCIENT_EVENTS,
] as const;
