export const PersianCalendarHolidays = [
    { holiday: true, month: 1, day: 1, type: "Iran", title: "آغاز عید نوروز" },
    { holiday: true, month: 1, day: 2, type: "Iran", title: "عید نوروز" },
    { holiday: false, month: 1, day: 2, type: "Iran", title: "هجوم به مدرسهٔ فیضیهٔ قم (۱۳۴۲ ه‍.ش)" },
    { holiday: false, month: 1, day: 2, type: "Iran", title: "آغاز عملیات فتح‌المبین (۱۳۶۱ ه‍.ش)" },
    { holiday: true, month: 1, day: 3, type: "Iran", title: "عید نوروز" },
    { holiday: true, month: 1, day: 4, type: "Iran", title: "عید نوروز" },
    { holiday: false, month: 1, day: 7, type: "Iran", title: "روز هنرهای نمایشی" },
    { holiday: true, month: 1, day: 12, type: "Iran", title: "روز جمهوری اسلامی ایران" },
    { holiday: true, month: 1, day: 13, type: "Iran", title: "روز طبیعت" },
    { holiday: false, month: 1, day: 18, type: "Iran", title: "روز سلامتی" },
    { holiday: false, month: 1, day: 20, type: "Iran", title: "روز ملی فناوری هسته‌ای" },
    { holiday: false, month: 1, day: 20, type: "Iran", title: "روز هنر انقلاب اسلامی" },
    { holiday: false, month: 1, day: 20, type: "Iran", title: "شهادت سید مرتضی آوینی (۱۳۷۲ ه‍.ش)" },
    { holiday: false, month: 1, day: 21, type: "Iran", title: "شهادت امیر سپهبد علی صیاد شیرازی (۱۳۷۸ ه‍.ش)" },
    { holiday: false, month: 1, day: 21, type: "Iran", title: "سالروز افتتاح حساب شمارهٔ ۱۰۰ و تأسیس بنیاد مسکن انقلاب اسلامی (۱۳۵۸ ه‍.ش)" },
    { holiday: false, month: 1, day: 25, type: "Iran", title: "روز بزرگداشت عطار نیشابوری" },
    { holiday: false, month: 1, day: 29, type: "Iran", title: "روز ارتش جمهوری اسلامی و نیروی زمینی" },
    { holiday: false, month: 2, day: 1, type: "Iran", title: "روز بزرگداشت سعدی" },
    { holiday: false, month: 2, day: 2, type: "Iran", title: "تأسیس سپاه پاسداران انقلاب اسلامی (۱۳۵۸ ه‍.ش)" },
    { holiday: false, month: 2, day: 2, type: "Iran", title: "اعلام انقلاب فرهنگی (۱۳۵۹ ه‍.ش)" },
    { holiday: false, month: 2, day: 3, type: "Iran", title: "روز بزرگداشت شیخ بهایی" },
    { holiday: false, month: 2, day: 5, type: "Iran", title: "شکست حملهٔ نظامی آمریکا به ایران در طبس (۱۳۵۹ ه‍.ش)" },
    { holiday: false, month: 2, day: 9, type: "Iran", title: "روز شوراها" },
    { holiday: false, month: 2, day: 10, type: "Iran", title: "روز ملی خلیج فارس" },
    { holiday: false, month: 2, day: 12, type: "Iran", title: "شهادت استاد مرتضی مطهری (۱۳۵۸ ه‍.ش)" },
    { holiday: false, month: 2, day: 12, type: "Iran", title: "روز معلم" },
    { holiday: false, month: 2, day: 15, type: "Iran", title: "روز بزرگداشت شیخ صدوق" },
    { holiday: false, month: 2, day: 18, type: "Iran", title: "روز بیماری‌های خاص و صعب‌العلاج" },
    { holiday: false, month: 2, day: 19, type: "Iran", title: "روز بزرگداشت شیخ کلینی" },
    { holiday: false, month: 2, day: 24, type: "Iran", title: "لغو امتیاز تنباکو به فتوای آیت‌الله میرزا حسن شیرازی (۱۲۷۰ ه‍.ش)" },
    { holiday: false, month: 2, day: 25, type: "Iran", title: "روز پاسداشت زبان فارسی و بزرگداشت حکیم ابوالقاسم فردوسی" },
    { holiday: false, month: 2, day: 28, type: "Iran", title: "روز بزرگداشت حکیم عمر خیام" },
    { holiday: false, month: 2, day: 30, type: "Iran", title: "روز ملی جمعیت" },
    { holiday: false, month: 2, day: 31, type: "Iran", title: "روز اهدای عضو، اهدای زندگی" },
    { holiday: false, month: 3, day: 1, type: "Iran", title: "روز بهره‌وری و بهینه‌سازی مصرف" },
    { holiday: false, month: 3, day: 1, type: "Iran", title: "روز بزرگداشت ملاصدرا (صدرالمتألهین)" },
    { holiday: false, month: 3, day: 3, type: "Iran", title: "فتح خرمشهر در عملیات بیت‌المقدس (۱۳۶۱ ه‍.ش) و روز مقاومت، ایثار و پیروزی" },
    { holiday: false, month: 3, day: 4, type: "Iran", title: "روز دزفول" },
    { holiday: false, month: 3, day: 4, type: "Iran", title: " روز مقاومت و پایداری" },
    { holiday: true, month: 3, day: 14, type: "Iran", title: "رحلت امام خمینی رهبر انقلاب اسلامی (۱۳۶۸ ه‍.ش)" },
    { holiday: false, month: 3, day: 14, type: "Iran", title: "انتخاب آیت‌الله خامنه‌ای به رهبری (۱۳۶۸ ه‍.ش)" },
    { holiday: true, month: 3, day: 15, type: "Iran", title: "قیام خونین ۱۵ خرداد (۱۳۴۲ ه‍.ش)" },
    { holiday: false, month: 3, day: 26, type: "Iran", title: "شهادت بخارایی، امانی، صفار هرندی و نیک‌نژاد از اعضای فدائیان اسلام (۱۳۴۴ ه‍.ش)" },
    { holiday: false, month: 3, day: 27, type: "Iran", title: "روز جهاد کشاورزی (تشکیل جهاد سازندگی، ۱۳۵۸ ه‍.ش)" },
    { holiday: false, month: 3, day: 29, type: "Iran", title: "درگذشت دکتر علی شریعتی (۱۳۵۶ ه‍.ش)" },
    { holiday: false, month: 3, day: 31, type: "Iran", title: "شهادت دکتر مصطفی چمران (۱۳۶۰ ه‍.ش)" },
    { holiday: false, month: 3, day: 31, type: "Iran", title: "روز بسیج استادان" },
    { holiday: false, month: 4, day: 1, type: "Iran", title: "روز تبلیغ و اطلاع‌رسانی دینی (تأسیس سازمان تبلیغات اسلامی ۱۳۶۰ ه‍.ش)" },
    { holiday: false, month: 4, day: 1, type: "Iran", title: "روز اصناف" },
    { holiday: false, month: 4, day: 7, type: "Iran", title: "شهادت آیت‌الله دکتر بهشتی و ۷۲ تن از یاران (۱۳۶۰ ه‍.ش)" },
    { holiday: false, month: 4, day: 7, type: "Iran", title: "روز قوهٔ قضاییه" },
    { holiday: false, month: 4, day: 8, type: "Iran", title: "روز مبارزه با سلاح‌های شیمیایی و میکروبی" },
    { holiday: false, month: 4, day: 10, type: "Iran", title: "روز صنعت و معدن" },
    { holiday: false, month: 4, day: 11, type: "Iran", title: "شهادت آیت‌الله صدوقی (۱۳۶۱ ه‍.ش)" },
    { holiday: false, month: 4, day: 12, type: "Iran", title: "حملهٔ ناوگان آمریکا به هواپیمای مسافربری ایران (۱۳۶۷ ه‍.ش)" },
    { holiday: false, month: 4, day: 12, type: "Iran", title: "روز افشای حقوق بشر آمریکایی" },
    { holiday: false, month: 4, day: 14, type: "Iran", title: "روز شهرداری و دهیاری" },
    { holiday: false, month: 4, day: 14, type: "Iran", title: "روز قلم" },
    { holiday: false, month: 4, day: 18, type: "Iran", title: "روز ادبیات کودکان و نوجوانان" },
    { holiday: false, month: 4, day: 21, type: "Iran", title: "روز عفاف و حجاب" },
    { holiday: false, month: 4, day: 23, type: "Iran", title: "روز گفت‌وگو و تعامل سازنده با جهان" },
    { holiday: false, month: 4, day: 25, type: "Iran", title: "روز بهزیستی و تامین اجتماعی" },
    { holiday: false, month: 4, day: 26, type: "Iran", title: "سالروز تأسیس نهاد شورای نگهبان" },
    { holiday: false, month: 5, day: 5, type: "Iran", title: "سالروز عملیات مرصاد (۱۳۶۷ ه‍.ش)" },
    { holiday: false, month: 5, day: 9, type: "Iran", title: "روز اهدای خون" },
    { holiday: false, month: 5, day: 14, type: "Iran", title: "صدور فرمان مشروطیت (۱۲۸۵ ه‍.ش)" },
    { holiday: false, month: 5, day: 14, type: "Iran", title: "روز حقوق بشر اسلامی و کرامت انسانی" },
    { holiday: false, month: 5, day: 16, type: "Iran", title: "تشکیل جهاد دانشگاهی (۱۳۵۹ ه‍.ش)" },
    { holiday: false, month: 5, day: 17, type: "Iran", title: "روز خبرنگار" },
    { holiday: false, month: 5, day: 21, type: "Iran", title: "روز حمایت از صنایع کوچک" },
    { holiday: false, month: 5, day: 22, type: "Iran", title: "روز تشکل‌ها و مشارکت‌های اجتماعی" },
    { holiday: false, month: 5, day: 23, type: "Iran", title: "روز مقاومت اسلامی" },
    { holiday: false, month: 5, day: 26, type: "Iran", title: "آغاز بازگشت آزادگان به ایران (۱۳۶۹ ه‍.ش)" },
    { holiday: false, month: 5, day: 28, type: "Iran", title: "کودتای ۲۸ مرداد (۱۳۳۲ ه‍.ش)" },
    { holiday: false, month: 5, day: 28, type: "Iran", title: "آتش‌سوزی سینما رکس آبادان (۱۳۵۷ ه‍.ش)" },
    { holiday: false, month: 5, day: 30, type: "Iran", title: "روز بزرگداشت علامه مجلسی" },
    { holiday: false, month: 6, day: 1, type: "Iran", title: "روز بزرگداشت ابوعلی سینا" },
    { holiday: false, month: 6, day: 1, type: "Iran", title: "روز پزشک" },
    { holiday: false, month: 6, day: 2, type: "Iran", title: "آغاز هفتهٔ دولت" },
    { holiday: false, month: 6, day: 2, type: "Iran", title: "شهادت سید علی اندرزگو (۱۳۵۷ ه‍.ش)" },
    { holiday: false, month: 6, day: 4, type: "Iran", title: "روز کارمند" },
    { holiday: false, month: 6, day: 5, type: "Iran", title: "روز بزرگداشت محمد بن زکریای رازی" },
    { holiday: false, month: 6, day: 5, type: "Iran", title: "روز داروسازی" },
    { holiday: false, month: 6, day: 5, type: "Iran", title: "روز کشتی" },
    { holiday: false, month: 6, day: 8, type: "Iran", title: "روز مبارزه با تروریسم (انفجار دفتر نخست‌وزیری و شهادت رجایی و باهنر - ۱۳۶۰ ه‍.ش)" },
    { holiday: false, month: 6, day: 12, type: "Iran", title: "روز مبارزه با استعمار انگلیس (سالروز شهادت رئیس‌علی دلواری)" },
    { holiday: false, month: 6, day: 13, type: "Iran", title: "روز تعاون" },
    { holiday: false, month: 6, day: 13, type: "Iran", title: "روز بزرگداشت ابوریحان بیرونی" },
    { holiday: false, month: 6, day: 14, type: "Iran", title: "شهادت آیت‌الله قدوسی و سرتیپ وحید دستجردی (۱۳۶۰ ه‍.ش)" },
    { holiday: false, month: 6, day: 17, type: "Iran", title: "قیام ۱۷ شهریور و کشتار جمعی از مردم به دست مأموران پهلوی (۱۳۵۷ ه‍.ش)" },
    { holiday: false, month: 6, day: 19, type: "Iran", title: "وفات آیت‌الله سید محمود طالقانی اولین امام جمعهٔ تهران (۱۳۵۸ ه‍.ش)" },
    { holiday: false, month: 6, day: 20, type: "Iran", title: "شهادت آیت‌الله مدنی (۱۳۶۰ ه‍.ش)" },
    { holiday: false, month: 6, day: 21, type: "Iran", title: "روز سینما" },
    { holiday: false, month: 6, day: 27, type: "Iran", title: "روز شعر و ادب فارسی" },
    { holiday: false, month: 6, day: 27, type: "Iran", title: "روز بزرگداشت استاد سید محمدحسین شهریار" },
    { holiday: false, month: 6, day: 31, type: "Iran", title: "آغاز جنگ تحمیلی (۱۳۵۹ ه‍.ش)" },
    { holiday: false, month: 6, day: 31, type: "Iran", title: "آغاز هفتهٔ دفاع مقدس" },
    { holiday: false, month: 7, day: 5, type: "Iran", title: "شکست حصر آبادان در عملیات ثامن‌الأئمه (ع) (۱۳۶۰ ه‍.ش)" },
    { holiday: false, month: 7, day: 7, type: "Iran", title: "روز بزرگداشت فرماندهان شهید دفاع مقدس" },
    { holiday: false, month: 7, day: 7, type: "Iran", title: "شهادت فلاحی، فکوری، نامجو، کلاهدوز و جهان‌آرا از فرماندهان ارتش و سپاه (۱۳۶۰ ه‍.ش)" },
    { holiday: false, month: 7, day: 7, type: "Iran", title: "روز آتش‌نشانی و ایمنی" },
    { holiday: false, month: 7, day: 7, type: "Iran", title: "روز بزرگداشت شمس" },
    { holiday: false, month: 7, day: 8, type: "Iran", title: "روز بزرگداشت مولوی" },
    { holiday: false, month: 7, day: 9, type: "Iran", title: "روز همبستگی و همدردی با کودکان و نوجوانان فلسطینی" },
    { holiday: false, month: 7, day: 13, type: "Iran", title: "هجرت امام خمینی از عراق به پاریس (۱۳۵۷ ه‍.ش)" },
    { holiday: false, month: 7, day: 13, type: "Iran", title: "روز نیروی انتظامی" },
    { holiday: false, month: 7, day: 14, type: "Iran", title: "روز دامپزشکی" },
    { holiday: false, month: 7, day: 15, type: "Iran", title: "روز روستا و عشایر" },
    { holiday: false, month: 7, day: 20, type: "Iran", title: "روز بزرگداشت حافظ" },
    { holiday: false, month: 7, day: 23, type: "Iran", title: "شهادت آیت‌الله اشرفی اصفهانی (۱۳۶۱ ه‍.ش)" },
    { holiday: false, month: 7, day: 24, type: "Iran", title: "روز ملی پارالمپیک" },
    { holiday: false, month: 7, day: 26, type: "Iran", title: "روز تربیت بدنی و ورزش" },
    { holiday: false, month: 8, day: 4, type: "Iran", title: "اعتراض امام خمینی علیه پذیرش کاپیتولاسیون (۱۳۴۳ ه‍.ش)" },
    { holiday: false, month: 8, day: 8, type: "Iran", title: "شهادت محمد حسین فهمیده (بسیجی ۱۳ ساله)" },
    { holiday: false, month: 8, day: 8, type: "Iran", title: "روز نوجوان و بسیج دانش‌آموزی" },
    { holiday: false, month: 8, day: 10, type: "Iran", title: "شهادت آیت‌الله قاضی طباطبایی (۱۳۵۸ ه‍.ش)" },
    { holiday: false, month: 8, day: 13, type: "Iran", title: "تسخیر سفارت آمریکا (۱۳۵۸ ه‍.ش)" },
    { holiday: false, month: 8, day: 13, type: "Iran", title: "روز ملی مبارزه با استکبار جهانی" },
    { holiday: false, month: 8, day: 13, type: "Iran", title: "روز دانش‌آموز" },
    { holiday: false, month: 8, day: 14, type: "Iran", title: "روز فرهنگ عمومی" },
    { holiday: false, month: 8, day: 24, type: "Iran", title: "روز کتاب، کتابخوانی و کتابدار" },
    { holiday: false, month: 8, day: 24, type: "Iran", title: "روز بزرگداشت آیت‌الله علامه سید محمد حسین طباطبایی (۱۳۶۰ ه‍.ش)" },
    { holiday: false, month: 9, day: 5, type: "Iran", title: "سالروز قیام مردم گرگان (۱۳۵۷ ه‍.ش)" },
    { holiday: false, month: 9, day: 5, type: "Iran", title: "تشکیل بسیج مستضعفان (۱۳۵۸ ه‍.ش)" },
    { holiday: false, month: 9, day: 7, type: "Iran", title: "روز نیروی دریایی" },
    { holiday: false, month: 9, day: 9, type: "Iran", title: "روز بزرگداشت شیخ مفید" },
    { holiday: false, month: 9, day: 10, type: "Iran", title: "شهادت آیت‌الله سید حسن مدرس (۱۳۱۶ ه‍.ش)" },
    { holiday: false, month: 9, day: 10, type: "Iran", title: "روز مجلس" },
    { holiday: false, month: 9, day: 12, type: "Iran", title: "روز قانون اساسی جمهوری اسلامی ایران (تصویب قانون اساسی جمهوری اسلامی ایران - ۱۳۵۸ ه‍.ش)" },
    { holiday: false, month: 9, day: 16, type: "Iran", title: "روز دانشجو" },
    { holiday: false, month: 9, day: 19, type: "Iran", title: "تشکیل شورای عالی انقلاب فرهنگی (۱۳۶۳ ه‍.ش)" },
    { holiday: false, month: 9, day: 20, type: "Iran", title: "شهادت آیت‌الله دستغیب (۱۳۶۰ ه‍.ش)" },
    { holiday: false, month: 9, day: 25, type: "Iran", title: "روز پژوهش" },
    { holiday: false, month: 9, day: 27, type: "Iran", title: "شهادت آیت‌الله دکتر محمد مفتح (۱۳۵۸ ه‍.ش)" },
    { holiday: false, month: 9, day: 27, type: "Iran", title: "روز وحدت حوزه و دانشگاه" },
    { holiday: false, month: 9, day: 30, type: "Iran", title: "شب یلدا (چله)" },
    { holiday: false, month: 10, day: 5, type: "Iran", title: "روز ایمنی در برابر زلزله و کاهش اثرات بلایای طبیعی" },
    { holiday: false, month: 10, day: 7, type: "Iran", title: "تشکیل نهضت سوادآموزی (۱۳۵۸ ه‍.ش)" },
    { holiday: false, month: 10, day: 19, type: "Iran", title: "قیام خونین مردم قم (۱۳۵۶ ه‍.ش)" },
    { holiday: false, month: 10, day: 20, type: "Iran", title: "شهادت میرزاتقی‌خان امیرکبیر (۱۲۳۰ ه‍.ش)" },
    { holiday: false, month: 10, day: 22, type: "Iran", title: "تشکیل شورای انقلاب (۱۳۵۷ ه‍.ش)" },
    { holiday: false, month: 10, day: 26, type: "Iran", title: "خروج شاه از ایران (۱۳۵۷ ه‍.ش)" },
    { holiday: false, month: 10, day: 27, type: "Iran", title: "شهادت نواب صفوی، طهماسبی، برادران واحدی و ذوالقدر از اعضای فداییان اسلام (۱۳۳۴ ه‍.ش)" },
    { holiday: false, month: 10, day: 29, type: "Iran", title: "روز غزه" },
    { holiday: false, month: 11, day: 6, type: "Iran", title: "سالروز حماسهٔ مردم آمل" },
    { holiday: false, month: 11, day: 12, type: "Iran", title: "بازگشت امام خمینی به ایران (۱۳۵۷ ه‍.ش) و آغاز دههٔ فجر انقلاب اسلامی" },
    { holiday: false, month: 11, day: 14, type: "Iran", title: "روز فناوری فضایی" },
    { holiday: false, month: 11, day: 19, type: "Iran", title: "روز نیروی هوایی" },
    { holiday: true, month: 11, day: 22, type: "Iran", title: "پیروزی انقلاب اسلامی ایران و سقوط نظام شاهنشاهی (۱۳۵۷ ه‍.ش)" },
    { holiday: false, month: 11, day: 29, type: "Iran", title: "قیام مردم تبریز به مناسبت چهلمین روز شهادت شهدای قم (۱۳۵۶ ه‍.ش)" },
    { holiday: false, month: 11, day: 29, type: "Iran", title: "روز اقتصاد مقاومتی و کارآفرینی" },
    { holiday: false, month: 12, day: 5, type: "Iran", title: "روز بزرگداشت خواجه نصیرالدین طوسی" },
    { holiday: false, month: 12, day: 5, type: "Iran", title: "روز مهندسی" },
    { holiday: false, month: 12, day: 14, type: "Iran", title: "روز احسان و نیکوکاری" },
    { holiday: false, month: 12, day: 15, type: "Iran", title: "روز درختکاری" },
    { holiday: false, month: 12, day: 18, type: "Iran", title: "روز بزرگداشت سید جمال‌الدین اسدآبادی" },
    { holiday: false, month: 12, day: 18, type: "Iran", title: "سالروز تأسیس کانون‌های فرهنگی و هنری مساجد کشور" },
    { holiday: false, month: 12, day: 20, type: "Iran", title: "روز راهیان نور" },
    { holiday: false, month: 12, day: 21, type: "Iran", title: "روز بزرگداشت نظامی گنجوی" },
    { holiday: false, month: 12, day: 22, type: "Iran", title: "روز بزرگداشت شهدا (تأسیس بنیاد شهید انقلاب اسلامی - ۱۳۵۸ ه‍.ش)" },
    { holiday: false, month: 12, day: 25, type: "Iran", title: "روز بزرگداشت پروین اعتصامی" },
    { holiday: true, month: 12, day: 29, type: "Iran", title: "روز ملی شدن صنعت نفت ایران (۱۳۲۹ ه‍.ش)" },
    { holiday: false, month: 1, day: 10, type: "Iran", title: "همه‌پرسی تغییر نظام شاهنشاهی به جمهوری اسلامی ایران (۱۳۵۸ ه‍.ش)" },
    { holiday: false, month: 1, day: 15, type: "Iran", title: "روز ذخایر ژنتیکی و زیستی" },
    { holiday: false, month: 1, day: 19, type: "Iran", title: "شهادت آیت‌الله سید محمد باقر صدر و خواهرشان بنت‌الهدی (۱۳۵۹ ه‍.ش)" },
    { holiday: false, month: 1, day: 20, type: "Iran", title: "قطع مناسبات سیاسی ایران و آمریکا (۱۳۵۹ ه‍.ش)" },
    { holiday: false, month: 2, day: 2, type: "Iran", title: "روز زمین پاک" },
    { holiday: false, month: 2, day: 7, type: "Iran", title: "روز ایمنی حمل‌ونقل" },
    { holiday: false, month: 2, day: 10, type: "Iran", title: "آغاز عملیات بیت المقدس (۱۳۶۱ ه‍.ش)" },
    { holiday: false, month: 2, day: 11, type: "Iran", title: "روز جهانی کارگر (۱ مه)" },
    { holiday: false, month: 2, day: 19, type: "Iran", title: "روز اسناد ملی و میراث مکتوب" },
    { holiday: false, month: 3, day: 5, type: "Iran", title: "روز نسیم مهر (روز حمایت از خانوادهٔ زندانیان)" },
    { holiday: false, month: 3, day: 7, type: "Iran", title: "افتتاح اولین دورهٔ مجلس شورای اسلامی (۱۳۵۹ ه‍.ش)" },
    { holiday: false, month: 3, day: 15, type: "Iran", title: "زندانی شدن امام خمینی (۱۳۴۲ ه‍.ش)" },
    { holiday: false, month: 3, day: 20, type: "Iran", title: "شهادت آیت‌الله سعیدی (۱۳۴۹ ه‍.ش)" },
    { holiday: false, month: 3, day: 25, type: "Iran", title: "روز گل و گیاه" },
    { holiday: false, month: 3, day: 30, type: "Iran", title: "شهادت زائران حرم رضوی (ع) (عاشورای ۱۳۷۳ ه‍.ش)" },
    { holiday: false, month: 4, day: 10, type: "Iran", title: "روز آزادسازی شهر مهران" },
    { holiday: false, month: 4, day: 12, type: "Iran", title: "روز بزرگداشت علامه امینی (۱۳۴۹ ه‍.ش)" },
    { holiday: false, month: 4, day: 16, type: "Iran", title: "روز مالیات" },
    { holiday: false, month: 4, day: 21, type: "Iran", title: "کشف توطئهٔ کودتا در پایگاه هوایی شهید نوژه (۱۳۵۹ ه‍.ش)" },
    { holiday: false, month: 4, day: 18, type: "Iran", title: "کشف کودتای نوژه (۱۳۵۹ ه‍.ش)" },
    { holiday: false, month: 4, day: 21, type: "Iran", title: "حمله به مسجد گوهرشاد و کشتار مردم (۱۳۱۴ ه‍.ش)" },
    { holiday: false, month: 4, day: 23, type: "Iran", title: "گشایش نخستین مجلس خبرگان رهبری (۱۳۶۲ ه‍.ش)" },
    { holiday: false, month: 4, day: 27, type: "Iran", title: "اعلام پذیرش قطعنامهٔ ۵۹۸ شورای امنیت از سوی ایران (۱۳۶۷ ه‍.ش)" },
    { holiday: false, month: 4, day: 30, type: "Iran", title: "روز بزرگداشت آیت‌الله سیدابوالقاسم کاشانی" },
    { holiday: false, month: 5, day: 6, type: "Iran", title: "روز کارآفرینی و آموزش‌های فنی و حرفه‌ای" },
    { holiday: false, month: 5, day: 8, type: "Iran", title: "روز بزرگداشت شیخ شهاب‌الدین سهروردی (شیخ اشراق)" },
    { holiday: false, month: 5, day: 11, type: "Iran", title: "شهادت آیت‌الله شیخ فضل‌الله نوری (۱۲۸۸ ه‍.ش)" },
    { holiday: false, month: 5, day: 28, type: "Iran", title: "گشایش مجلس خبرگان برای بررسی نهایی قانون اساسی جمهوری اسلامی ایران (۱۳۵۸ ه‍.ش)" },
    { holiday: false, month: 5, day: 31, type: "Iran", title: "روز صنعت دفاعی" },
    { holiday: false, month: 6, day: 3, type: "Iran", title: "اشغال ایران به دست متفقین (۱۳۲۰ ه‍.ش)" },
    { holiday: false, month: 6, day: 10, type: "Iran", title: "تصویب قانون عملیات بانکی بدون ربا (۱۳۶۲ ه‍.ش)" },
    { holiday: false, month: 6, day: 10, type: "Iran", title: "روز بانکداری اسلامی" },
    { holiday: false, month: 6, day: 11, type: "Iran", title: "روز صنعت چاپ" },
    { holiday: false, month: 6, day: 12, type: "Iran", title: "روز بهورز" },
    { holiday: false, month: 6, day: 13, type: "Iran", title: "روز مردم‌شناسی" },
    { holiday: false, month: 6, day: 30, type: "Iran", title: "روز گفت‌وگوی تمدن‌ها" },
    { holiday: false, month: 7, day: 20, type: "Iran", title: "روز اسکان معلولان و سالمندان" },
    { holiday: false, month: 7, day: 24, type: "Iran", title: "روز پیوند اولیا و مربیان" },
    { holiday: false, month: 7, day: 24, type: "Iran", title: "به آتش کشیده‌شدن مسجد جامع شهر کرمان (۱۳۵۷ ه‍.ش)" },
    { holiday: false, month: 7, day: 29, type: "Iran", title: "روز صادرات" },
    { holiday: false, month: 8, day: 1, type: "Iran", title: "شهادت آیت‌الله حاج سید مصطفی خمینی (۱۳۵۶ ه‍.ش)" },
    { holiday: false, month: 8, day: 1, type: "Iran", title: "روز آمار و برنامه‌ریزی" },
    { holiday: false, month: 8, day: 8, type: "Iran", title: "روز پدافند غیرعامل" },
    { holiday: false, month: 8, day: 13, type: "Iran", title: "تبعید امام خمینی از ایران به ترکیه (۱۳۴۳ ه‍.ش)" },
    { holiday: false, month: 8, day: 18, type: "Iran", title: "روز کیفیت" },
    { holiday: false, month: 8, day: 26, type: "Iran", title: "آزادسازی سوسنگرد" },
    { holiday: false, month: 9, day: 11, type: "Iran", title: "شهادت میرزا کوچک خان جنگلی (۱۳۰۰ ه‍.ش)" },
    { holiday: false, month: 9, day: 13, type: "Iran", title: "روز بیمه" },
    { holiday: false, month: 9, day: 18, type: "Iran", title: "معرفی عراق به عنوان مسئول و آغازگر جنگ از سوی سازمان ملل (۱۳۷۰ ه‍.ش)" },
    { holiday: false, month: 9, day: 26, type: "Iran", title: "روز حمل و نقل و رانندگان" },
    { holiday: false, month: 9, day: 29, type: "Iran", title: "روز تجلیل از شهید تندگویان" },
    { holiday: false, month: 10, day: 3, type: "Iran", title: "روز ثبت احوال" },
    { holiday: false, month: 10, day: 7, type: "Iran", title: "شهادت آیت‌الله حسین غفاری (۱۳۵۳ ه‍.ش)" },
    { holiday: false, month: 10, day: 8, type: "Iran", title: "روز صنعت پتروشیمی" },
    { holiday: false, month: 10, day: 9, type: "Iran", title: "۹ دی" },
    { holiday: false, month: 10, day: 13, type: "Iran", title: "ابلاغ پیام تاریخی امام خمینی به گورباچف رهبر شوروی سابق (۱۳۶۷ ه‍.ش)" },
    { holiday: false, month: 10, day: 17, type: "Iran", title: "اجرای طرح حذف حجاب (۱۳۱۴ ه‍.ش)" },
    { holiday: false, month: 11, day: 5, type: "Iran", title: "انتخابات اولین دورهٔ ریاست جمهوری (۱۳۵۸ ه‍.ش)" },
    { holiday: false, month: 11, day: 21, type: "Iran", title: "شکسته شدن حکومت نظامی به فرمان امام خمینی (۱۳۵۷ ه‍.ش)" },
    { holiday: false, month: 11, day: 25, type: "Iran", title: "صدور حکم امام خمینی مبنی بر ارتداد سلمان رشدی (۱۳۶۷ ه‍.ش)" },
    { holiday: false, month: 12, day: 3, type: "Iran", title: "کودتای رضاخان (۱۲۹۹ ه‍.ش)" },
    { holiday: false, month: 12, day: 8, type: "Iran", title: "روز امور تربیتی و تربیت اسلامی" },
    { holiday: false, month: 12, day: 9, type: "Iran", title: "روز ملی حمایت از حقوق مصرف‌کنندگان" },
    { holiday: false, month: 12, day: 24, type: "Iran", title: "برگزاری انتخابات اولین دورهٔ مجلس شورای اسلامی (۱۳۵۸ ه‍.ش)" },
    { holiday: false, month: 12, day: 25, type: "Iran", title: "بمباران شیمیایی حلبچه توسط ارتش بعث عراق (۱۳۶۶ ه‍.ش)" },
    { holiday: false, month: 1, day: 6, type: "Ancient Iran", title: "روز امید، روز شادباش‌نویسی" },
    { holiday: false, month: 1, day: 10, type: "Ancient Iran", title: "جشن آبانگاه" },
    { holiday: false, month: 1, day: 13, type: "Ancient Iran", title: "جشن سیزده‌بدر" },
    { holiday: false, month: 1, day: 17, type: "Ancient Iran", title: "سروش‌روز، جشن سروشگان" },
    { holiday: false, month: 1, day: 19, type: "Ancient Iran", title: "فرورین‌روز، جشن فروردینگان" },
    { holiday: false, month: 2, day: 2, type: "Ancient Iran", title: "جشن گیاه‌آوری" },
    { holiday: false, month: 2, day: 3, type: "Ancient Iran", title: "اردیبهشت‌روز، جشن اردیبهشتگان" },
    { holiday: false, month: 2, day: 10, type: "Ancient Iran", title: "جشن چهلم نوروز" },
    { holiday: false, month: 2, day: 15, type: "Ancient Iran", title: "گاهنبار میدیوزَرِم، جشن میانهٔ بهار، جشن بهاربُد / روز پیام‌آوری زرتشت" },
    { holiday: false, month: 3, day: 1, type: "Ancient Iran", title: "ارغاسوان، جشن گرما" },
    { holiday: false, month: 3, day: 6, type: "Ancient Iran", title: "خردادروز، جشن خردادگان" },
    { holiday: false, month: 4, day: 1, type: "Ancient Iran", title: "جشن آب‌پاشونک، جشن آغاز تابستان / سال نو در گاهشماری گاهنباری / دیدار طلوع خورشید در تقویم آفتابی چارتاقی نیاسر" },
    { holiday: false, month: 4, day: 6, type: "Ancient Iran", title: "جشن نیلوفر" },
    { holiday: false, month: 4, day: 13, type: "Ancient Iran", title: "تیرروز، جشن تیرگان" },
    { holiday: false, month: 4, day: 15, type: "Ancient Iran", title: "جشن خام‌خواری" },
    { holiday: false, month: 5, day: 7, type: "Ancient Iran", title: "مردادروز، جشن مردادگان" },
    { holiday: false, month: 5, day: 10, type: "Ancient Iran", title: "جشن چلهٔ تابستان" },
    { holiday: false, month: 5, day: 15, type: "Ancient Iran", title: "گاهنبار میدیوشِم، جشن میانهٔ تابستان" },
    { holiday: false, month: 5, day: 18, type: "Ancient Iran", title: "جشن مَی‌خواره" },
    { holiday: false, month: 6, day: 1, type: "Ancient Iran", title: "فغدیه، جشن خنکی هوا" },
    { holiday: false, month: 6, day: 3, type: "Ancient Iran", title: "جشن کشمین" },
    { holiday: false, month: 6, day: 4, type: "Ancient Iran", title: "شهریورروز، جشن شهریورگان / زادروز داراب (کوروش) / عروج مانی" },
    { holiday: false, month: 6, day: 8, type: "Ancient Iran", title: "خزان‌جشن" },
    { holiday: false, month: 6, day: 15, type: "Ancient Iran", title: "بازارجشن" },
    { holiday: false, month: 6, day: 31, type: "Ancient Iran", title: "گاهنبار پَتیَه‌شَهیم، جشن پایان تابستان" },
    { holiday: false, month: 7, day: 1, type: "Ancient Iran", title: "جشن میتراکانا / سال نو هخامنشی" },
    { holiday: false, month: 7, day: 12, type: "Ancient Iran", title: "آیین قالیشویان اردهال، بازماندی از تیرگان" },
    { holiday: false, month: 7, day: 13, type: "Ancient Iran", title: "تیرروز، جشن تیرروزی" },
    { holiday: false, month: 7, day: 16, type: "Ancient Iran", title: "مهرروز، جشن مهرگان" },
    { holiday: false, month: 7, day: 21, type: "Ancient Iran", title: "رام‌روز، جشن رام‌روزی / جشن پیروزی کاوه و فریدون" },
    { holiday: false, month: 8, day: 7, type: "Ancient Iran", title: " روز کوروش بزرگ" },
    { holiday: false, month: 8, day: 10, type: "Ancient Iran", title: "آبان‌روز، جشن آبانگان" },
    { holiday: false, month: 8, day: 15, type: "Ancient Iran", title: "گاهنبار اَیاثرَم، جشن میانهٔ پاییز" },
    { holiday: false, month: 9, day: 1, type: "Ancient Iran", title: "آذرجشن" },
    { holiday: false, month: 9, day: 9, type: "Ancient Iran", title: "آذرروز، جشن آذرگان" },
    { holiday: false, month: 9, day: 30, type: "Ancient Iran", title: "گاهنبار میدیارِم، جشن میانهٔ سال گاهنباری (از مبدأ آغاز تابستان)" },
    { holiday: false, month: 10, day: 1, type: "Ancient Iran", title: "روز میلاد خورشید، جشن خرم‌روز / نخستین جشن دیگان / دیدار طلوع خورشید در تقویم آفتابی چارتاقی نیاسر" },
    { holiday: false, month: 10, day: 5, type: "Ancient Iran", title: "بازارجشن" },
    { holiday: false, month: 10, day: 8, type: "Ancient Iran", title: "دی‌به‌آذرروز، دومین جشن دیگان" },
    { holiday: false, month: 10, day: 14, type: "Ancient Iran", title: "سیرسور، جشن گیاه‌خواری" },
    { holiday: false, month: 10, day: 15, type: "Ancient Iran", title: "جشن پیکرتراشی / دی‌به‌مهرروز، سومین جشن دیگان" },
    { holiday: false, month: 10, day: 16, type: "Ancient Iran", title: "جشن درامزینان، جشن درفش‌ها" },
    { holiday: false, month: 10, day: 23, type: "Ancient Iran", title: "دی‌به‌دین‌روز، چهارمین جشن دیگان" },
    { holiday: false, month: 11, day: 1, type: "Ancient Iran", title: "زادروز فردوسی" },
    { holiday: false, month: 11, day: 2, type: "Ancient Iran", title: "بهمن‌روز، جشن بهمنگان" },
    { holiday: false, month: 11, day: 4, type: "Ancient Iran", title: "شهریورروز، آغاز پادشاهی داراب (کوروش)" },
    { holiday: false, month: 11, day: 5, type: "Ancient Iran", title: "جشن نوسَره" },
    { holiday: false, month: 11, day: 10, type: "Ancient Iran", title: "آبان‌روز، جشن سَدَه، آتش‌افروزی بر بام‌ها / نمایش‌بازی همگانی" },
    { holiday: false, month: 11, day: 15, type: "Ancient Iran", title: "جشن میانهٔ زمستان" },
    { holiday: false, month: 11, day: 22, type: "Ancient Iran", title: "بادروز، جشن بادروزی" },
    { holiday: false, month: 12, day: 1, type: "Ancient Iran", title: "جشن اسفندی / جشن آبسالان، بهارجشن / نمایش‌بازی همگانی" },
    { holiday: false, month: 12, day: 5, type: "Ancient Iran", title: "اسفندروز، جشن اسفندگان، گرامیداشت زمین و بانوان / جشن برزگران" },
    { holiday: false, month: 12, day: 10, type: "Ancient Iran", title: "جشن وخشنکام" },
    { holiday: false, month: 12, day: 19, type: "Ancient Iran", title: "جشن نوروز رودها" },
    { holiday: false, month: 12, day: 20, type: "Ancient Iran", title: "جشن گلدان" },
    { holiday: false, month: 12, day: 25, type: "Ancient Iran", title: "هزارهٔ شاهنامه، هزارمین سالگرد پایان سرایش شاهنامهٔ فردوسی" },
    { holiday: false, month: 12, day: 26, type: "Ancient Iran", title: "فروردگان" },
    { holiday: false, month: 12, day: 29, type: "Ancient Iran", title: "گاهنبار هَمَسپَتمَدَم، جشن پایان زمستان (در آخرین روز سال) / جشن اوشیدر (نجات‌بخش ایرانی) در دریاچهٔ هامون و کوه خواجه / آتش‌افروزی بر بام‌ها در استقبال از نوروز" },
    { holiday: false, month: 1, day: 6, type: "Ancient Iran", title: "روز تولد زرتشت" },
    { holiday: false, month: 10, day: 5, type: "Ancient Iran", title: "روز درگذشت زرتشت" },
];



export const HijriCalendarHolidays = [
    { holiday: false, month: 1, day: 1, type: "Islamic Iran", title: "آغاز سال هجری قمری" },
    { holiday: true, month: 1, day: 9, type: "Islamic Iran", title: "تاسوعای حسینی" },
    { holiday: true, month: 1, day: 10, type: "Islamic Iran", title: "عاشورای حسینی" },
    { holiday: false, month: 1, day: 11, type: "Islamic Iran", title: "روز تجلیل از اسرا و مفقودان" },
    { holiday: false, month: 1, day: 12, type: "Islamic Iran", title: "شهادت امام زین‌العابدین (ع) (۹۵ ه‍.ق)" },
    { holiday: false, month: 1, day: 25, type: "Islamic Iran", title: "شهادت امام زین‌العابدین (ع) (۹۵ ه‍.ق) به روایتی" },
    { holiday: false, month: 2, day: 7, type: "Islamic Iran", title: "شهادت امام حسن مجتبی (ع) (۵۰ ه‍.ق) (به روایتی)" },
    { holiday: false, month: 2, day: 7, type: "Islamic Iran", title: "روز بزرگداشت سلمان فارسی" },
    { holiday: true, month: 2, day: 20, type: "Islamic Iran", title: "اربعین حسینی" },
    { holiday: false, month: 2, day: 27, type: "Islamic Iran", title: "روز وقف" },
    { holiday: true, month: 2, day: 28, type: "Islamic Iran", title: "رحلت حضرت رسول اکرم (ص) (۱۱ ه‍.ق) – شهادت امام حسن مجتبی (ع) (۵۰ ه‍.ق)" },
    { holiday: true, month: 2, day: 30, type: "Islamic Iran", title: "شهادت امام رضا (ع) (۲۰۳ ه‍.ق)" },
    { holiday: false, month: 3, day: 1, type: "Islamic Iran", title: "هجرت رسول اکرم (ص) از مکه به مدینه" },
    { holiday: true, month: 3, day: 8, type: "Islamic Iran", title: "شهادت امام حسن عسکری (ع) (۲۶۰ ه‍.ق) و آغاز امامت حضرت ولی عصر (عج)" },
    { holiday: false, month: 3, day: 12, type: "Islamic Iran", title: "ولادت حضرت رسول اکرم (ص) به روایت اهل سنت (۵۳ سال قبل از هجرت) - آغاز هفتهٔ وحدت" },
    { holiday: true, month: 3, day: 17, type: "Islamic Iran", title: "ولادت حضرت رسول اکرم (ص) (۵۳ سال قبل از هجرت) و روز اخلاق و مهرورزی" },
    { holiday: true, month: 3, day: 17, type: "Islamic Iran", title: "ولادت امام جعفر صادق (ع) مؤسس مذهب جعفری (۸۳ ه‍.ق)" },
    { holiday: false, month: 4, day: 8, type: "Islamic Iran", title: "ولادت امام حسن عسگری (ع) (۲۳۲ ه‍.ق)" },
    { holiday: false, month: 4, day: 10, type: "Islamic Iran", title: "وفات حضرت معصومه (س) (۲۰۱ ه‍.ق)" },
    { holiday: false, month: 5, day: 5, type: "Islamic Iran", title: "ولادت حضرت زینب (س) (۵ ه‍.ق) و روز پرستار" },
    { holiday: false, month: 5, day: 13, type: "Islamic Iran", title: "شهادت حضرت فاطمهٔ زهرا (س) (۱۱ ه‍.ق) به روایتی" },
    { holiday: true, month: 6, day: 3, type: "Islamic Iran", title: "شهادت حضرت فاطمهٔ زهرا (س) (۱۱ ه‍.ق)" },
    { holiday: false, month: 6, day: 13, type: "Islamic Iran", title: "سالروز وفات حضرت ام‌البنین (س) - روز تکریم مادران و همسران شهدا" },
    { holiday: false, month: 6, day: 20, type: "Islamic Iran", title: "روز زن و مادر و ولادت حضرت فاطمهٔ زهرا (س) (سال هشتم قبل از هجرت)" },
    { holiday: false, month: 6, day: 20, type: "Islamic Iran", title: "تولد امام خمینی (ره) رهبر کبیر انقلاب اسلامی (۱۳۲۰ ه‍.ق)" },
    { holiday: false, month: 7, day: 1, type: "Islamic Iran", title: "ولادت امام محمد باقر (ع) (۵۷ ه‍.ق)" },
    { holiday: false, month: 7, day: 3, type: "Islamic Iran", title: "شهادت امام علی النقی الهادی (ع) (۲۵۴ ه‍.ق)" },
    { holiday: false, month: 7, day: 10, type: "Islamic Iran", title: "ولادت امام محمد تقی (ع) (۱۹۵ ه‍.ق)" },
    { holiday: true, month: 7, day: 13, type: "Islamic Iran", title: "روز پدر و مرد و ولادت امام علی (ع) (۲۳ سال قبل از هجرت) – آغاز ایام‌البیض (اعتکاف)" },
    { holiday: false, month: 7, day: 15, type: "Islamic Iran", title: "وفات حضرت زینب (س) (۶۲ ه‍.ق)" },
    { holiday: false, month: 7, day: 15, type: "Islamic Iran", title: "تغییر قبلهٔ مسلمین از بیت‌المقدس به مکهٔ معظمه (۲ ه‍.ق)" },
    { holiday: false, month: 7, day: 25, type: "Islamic Iran", title: "شهادت امام موسی کاظم (ع) (۱۸۳ ه‍.ق)" },
    { holiday: true, month: 7, day: 27, type: "Islamic Iran", title: "مبعث حضرت رسول اکرم (ص) (۱۳ سال قبل از هجرت)" },
    { holiday: false, month: 8, day: 3, type: "Islamic Iran", title: "ولادت امام حسین (ع) (۴ ه‍.ق) و روز پاسدار" },
    { holiday: false, month: 8, day: 4, type: "Islamic Iran", title: "ولادت حضرت ابوالفضل العباس (ع) (۲۶ ه‍.ق) و روز جانباز" },
    { holiday: false, month: 8, day: 5, type: "Islamic Iran", title: "ولادت امام زین‌العابدین (ع) (۳۸ ه‍.ق)" },
    { holiday: false, month: 8, day: 11, type: "Islamic Iran", title: "ولادت حضرت علی اکبر (ع) (۳۳ ه‍.ق) و روز جوان" },
    { holiday: true, month: 8, day: 15, type: "Islamic Iran", title: "ولادت حضرت قائم (عج) (۲۵۵ ه‍.ق) و روز جهانی مستضعفان" },
    { holiday: false, month: 9, day: 10, type: "Islamic Iran", title: "وفات حضرت خدیجه (س) (۳ سال قبل از هجرت)" },
    { holiday: false, month: 9, day: 15, type: "Islamic Iran", title: "ولادت امام حسن مجتبی (ع) (۳ ه‍.ق) و روز اکرام" },
    { holiday: false, month: 9, day: 18, type: "Islamic Iran", title: "شب قدر" },
    { holiday: false, month: 9, day: 19, type: "Islamic Iran", title: "ضربت خوردن امام علی (ع) (۴۰ ه‍.ق)" },
    { holiday: false, month: 9, day: 20, type: "Islamic Iran", title: "شب قدر" },
    { holiday: true, month: 9, day: 21, type: "Islamic Iran", title: "شهادت امام علی (ع) (۴۰ ه‍.ق)" },
    { holiday: false, month: 9, day: 22, type: "Islamic Iran", title: "شب قدر" },
    { holiday: true, month: 10, day: 1, type: "Islamic Iran", title: "عید سعید فطر" },
	{ holiday: true, month: 10, day: 2, type: "Islamic Iran", title: "تعطیل به مناسبت عید سعید فطر" },
    { holiday: false, month: 10, day: 17, type: "Islamic Iran", title: "روز فرهنگ پهلوانی و ورزش زورخانه‌ای" },
    { holiday: true, month: 10, day: 25, type: "Islamic Iran", title: "شهادت امام جعفر صادق (ع) (۱۴۸ ه‍.ق)" },
    { holiday: false, month: 11, day: 1, type: "Islamic Iran", title: "ولادت حضرت معصومه (س) (۱۷۳ ه‍.ق) و روز دختر" },
    { holiday: false, month: 11, day: 5, type: "Islamic Iran", title: "روز تجلیل از امام‌زادگان و بقاع متبرکه" },
    { holiday: false, month: 11, day: 6, type: "Islamic Iran", title: "روز بزرگداشت حضرت احمدبن‌موسی شاهچراغ (ع)" },
    { holiday: false, month: 11, day: 11, type: "Islamic Iran", title: "ولادت امام رضا (ع) (۱۴۸ ه‍.ق)" },
    { holiday: false, month: 11, day: 30, type: "Islamic Iran", title: "شهادت امام محمد تقی (ع) (۲۲۰ ه‍.ق)" },
    { holiday: false, month: 12, day: 1, type: "Islamic Iran", title: "سالروز ازدواج امام علی (ع) و حضرت فاطمه (س) (۲ ه‍.ق) – روز ازدواج" },
    { holiday: false, month: 12, day: 6, type: "Islamic Iran", title: "شهادت زائران خانهٔ خدا به دست مأموران آل سعود (۱۳۶۶ ه‍.ش برابر با ۶ ذی‌الحجه ۱۴۰۷ ه‍.ق)" },
    { holiday: false, month: 12, day: 7, type: "Islamic Iran", title: "شهادت امام محمد باقر (ع) (۱۱۴ ه‍.ق)" },
    { holiday: false, month: 12, day: 9, type: "Islamic Iran", title: "روز عرفه (روز نیایش)" },
    { holiday: true, month: 12, day: 10, type: "Islamic Iran", title: "عید سعید قربان (عید الاضحی)" },
    { holiday: false, month: 12, day: 15, type: "Islamic Iran", title: "ولادت امام علی النقی الهادی (ع) (۲۱۲ ه‍.ق)" },
    { holiday: true, month: 12, day: 18, type: "Islamic Iran", title: "عید سعید غدیر خم (۱۰ ه‍.ق)" },
    { holiday: false, month: 12, day: 20, type: "Islamic Iran", title: "ولادت امام موسی کاظم (ع) (۱۲۸ ه‍.ق)" },
    { holiday: false, month: 12, day: 24, type: "Islamic Iran", title: "روز مباهلهٔ پیامبر اسلام (ص) (۱۰ ه‍.ق)" },
    { holiday: false, month: 12, day: 25, type: "Islamic Iran", title: "روز خانواده و تکریم بازنشستگان" },
    { holiday: false, month: 2, day: 3, type: "Islamic Iran", title: "ولادت امام محمد باقر (ع) (۵۷ ﻫ.ق) به روایتی" },
    { holiday: false, month: 3, day: 12, type: "Islamic Iran", title: "آغاز واجب شدن نماز، ورود پیامبر به مدینه" },
    { holiday: false, month: 3, day: 15, type: "Islamic Iran", title: "بنای مسجد قبا (اولین مسجد در اسلام)" },
    { holiday: false, month: 3, day: 16, type: "Islamic Iran", title: "ورود اهل بیت امام حسین (ع) به شام" },
    { holiday: false, month: 3, day: 17, type: "Islamic Iran", title: "بنای مسجدالنبی در مدینه" },
    { holiday: false, month: 3, day: 23, type: "Islamic Iran", title: "ورود حضرت معصومه (س) به قم" },
    { holiday: false, month: 3, day: 26, type: "Islamic Iran", title: "صلح امام حسن (ع)" },
    { holiday: false, month: 4, day: 3, type: "Islamic Iran", title: "سفر امام حسن (ع) به جرجان" },
    { holiday: false, month: 4, day: 4, type: "Islamic Iran", title: "ولادت شاه عبدالعظیم حسنی (ع)" },
    { holiday: false, month: 4, day: 8, type: "Islamic Iran", title: "شهادت حضرت فاطمهٔ زهرا (س) (۱۱ ﻫ.ق) به روایتی" },
    { holiday: false, month: 5, day: 10, type: "Islamic Iran", title: "وقوع جنگ جمل بین سپاهیان امام علی (ع) و ناکثین" },
    { holiday: false, month: 5, day: 27, type: "Islamic Iran", title: "وفات حضرت عبدالمطلب (ع)" },
    { holiday: false, month: 6, day: 12, type: "Islamic Iran", title: "حرکت پیامبر به سمت خیبر" },
    { holiday: false, month: 6, day: 19, type: "Islamic Iran", title: "ازدواج حضرت عبداللّه (ع) و آمنه (س)" },
    { holiday: false, month: 6, day: 21, type: "Islamic Iran", title: "ولادت حضرت ام‌کلثوم (س)" },
    { holiday: false, month: 7, day: 9, type: "Islamic Iran", title: "ولادت حضرت علی اصغر (ع)" },
    { holiday: false, month: 7, day: 16, type: "Islamic Iran", title: "خروج فاطمه بنت اسد از کعبه" },
    { holiday: false, month: 7, day: 23, type: "Islamic Iran", title: "مجروح شدن امام حسن مجتبی (ع) در ساباط مدائن" },
    { holiday: false, month: 7, day: 23, type: "Islamic Iran", title: "مسموم شدن امام موسی کاظم (ع) به دستور مأمون" },
    { holiday: false, month: 7, day: 24, type: "Islamic Iran", title: "فتح قلعهٔ خیبر توسط امام علی (ع)، بازگشت جعفر بن ابی‌طالب از حبشه" },
    { holiday: false, month: 7, day: 26, type: "Islamic Iran", title: "وفات حضرت ابوطالب (ع)" },
    { holiday: false, month: 7, day: 28, type: "Islamic Iran", title: "حرکت امام حسین (ع) از مدینه به مکه" },
    { holiday: false, month: 7, day: 30, type: "Islamic Iran", title: "هجرت مسلمانان به حبشه، غزوهٔ نخله" },
    { holiday: false, month: 8, day: 15, type: "Islamic Iran", title: "روز سربازان گمنام امام زمان (عج)" },
    { holiday: false, month: 10, day: 21, type: "Islamic Iran", title: "فتح اندلس به دست مسلمانان (۹۲ ه‍.ق)" },
    { holiday: false, month: 11, day: 5, type: "Islamic Iran", title: "روز بزرگداشت حضرت صالح بن موسی کاظم (ع)" }
];


export const GregorianCalendarHolidays = [
    { holiday: false, month: 1, day: 1, type: "Global", title: "آغاز سال میلادی" },
    { holiday: false, month: 1, day: 2, type: "Global", title: "روز جهانی گمرک" },
    { holiday: false, month: 2, day: 4, type: "Global", title: "روز جهانی سرطان" },
    { holiday: false, month: 2, day: 6, type: "Global", title: "روز جهانی مبارزه با ناقص‌سازی زنان" },
    { holiday: false, month: 2, day: 20, type: "Global", title: "روز جهانی عدالت اجتماعی" },
    { holiday: false, month: 2, day: 21, type: "Global", title: "روز جهانی زبان مادری" },
    { holiday: false, month: 3, day: 8, type: "Global", title: "روز جهانی زنان" },
    { holiday: false, month: 3, day: 22, type: "Global", title: "روز جهانی آب" },
    { holiday: false, month: 3, day: 23, type: "Global", title: "روز جهانی هواشناسی" },
    { holiday: false, month: 3, day: 24, type: "Global", title: "روز جهانی سل" },
    { holiday: false, month: 4, day: 7, type: "Global", title: "روز جهانی سلامت" },
    { holiday: false, month: 4, day: 22, type: "Global", title: "روز جهانی زمین پاک" },
    { holiday: false, month: 4, day: 23, type: "Global", title: "روز جهانی کتاب و حق مؤلف" },
    { holiday: false, month: 4, day: 25, type: "Global", title: "روز جهانی مالاریا" },
    { holiday: false, month: 4, day: 27, type: "Global", title: "روز جهانی گرافیک" },
    { holiday: false, month: 5, day: 1, type: "Global", title: "روز جهانی کارگر" },
    { holiday: false, month: 5, day: 3, type: "Global", title: "روز جهانی آزادی مطبوعات" },
    { holiday: false, month: 5, day: 5, type: "Global", title: "روز جهانی ماما" },
    { holiday: false, month: 5, day: 8, type: "Global", title: "روز جهانی صلیب سرخ و هلال احمر" },
    { holiday: false, month: 5, day: 15, type: "Global", title: "روز جهانی خانواده" },
    { holiday: false, month: 5, day: 17, type: "Global", title: "روز جهانی ارتباطات و روابط عمومی" },
    { holiday: false, month: 5, day: 18, type: "Global", title: "روز جهانی موزه و میراث فرهنگی" },
    { holiday: false, month: 5, day: 29, type: "Global", title: "روز جهانی حافظان صلح ملل متحد" },
    { holiday: false, month: 5, day: 31, type: "Global", title: "روز جهانی بدون دخانیات" },
    { holiday: false, month: 6, day: 1, type: "Global", title: "روز جهانی والدین" },
    { holiday: false, month: 6, day: 5, type: "Global", title: "روز جهانی محیط زیست" },
    { holiday: false, month: 6, day: 10, type: "Global", title: "روز جهانی صنایع دستی" },
    { holiday: false, month: 6, day: 12, type: "Global", title: "روز جهانی منع کار کودکان" },
    { holiday: false, month: 6, day: 14, type: "Global", title: "روز جهانی اهدا خون" },
    { holiday: false, month: 6, day: 14, type: "Global", title: "روز جهانی مادر" },
    { holiday: false, month: 6, day: 17, type: "Global", title: "روز جهانی بیابان‌زدایی" },
    { holiday: false, month: 6, day: 20, type: "Global", title: "روز جهانی پناهندگان" },
    { holiday: false, month: 6, day: 26, type: "Global", title: "روز جهانی مبارزه با مواد مخدر" },
    { holiday: false, month: 6, day: 26, type: "Global", title: "روز جهانی قربانیان خشونت" },
    { holiday: false, month: 6, day: 26, type: "Global", title: "روز جهانی جمعیت" },
    { holiday: false, month: 8, day: 1, type: "Global", title: "روز جهانی شیر مادر" },
    { holiday: false, month: 8, day: 6, type: "Global", title: "انفجار بمب اتمی آمریکا در هیروشیما با بیش از ۱۶۰ هزار کشته و مجروح (۱۹۴۵ میلادی)" },
    { holiday: false, month: 8, day: 12, type: "Global", title: "روز جهانی جوانان" },
    { holiday: false, month: 8, day: 13, type: "Global", title: "روز جهانی چپ دستان" },
    { holiday: false, month: 8, day: 19, type: "Global", title: "روز جهانی انسان دوستی" },
    { holiday: false, month: 8, day: 19, type: "Global", title: "روز جهانی عکاسی" },
    { holiday: false, month: 8, day: 21, type: "Global", title: "روز جهانی مسجد" },
    { holiday: false, month: 9, day: 1, type: "Global", title: "روز جهانی صلح" },
    { holiday: false, month: 9, day: 8, type: "Global", title: "روز جهانی با سوادی" },
    { holiday: false, month: 9, day: 10, type: "Global", title: "روز جهانی جلوگیری از خودکشی" },
    { holiday: false, month: 9, day: 21, type: "Global", title: "روز جهانی باسوادی و روز جهانی آلزایمر" },
    { holiday: false, month: 9, day: 27, type: "Global", title: "روز جهانی جهانگردی" },
    { holiday: false, month: 9, day: 30, type: "Global", title: "روز جهانی ناشنوایان" },
    { holiday: false, month: 9, day: 30, type: "Global", title: "روز جهانی دریانوردی" },
    { holiday: false, month: 10, day: 1, type: "Global", title: "روز جهانی سالمندان" },
    { holiday: false, month: 10, day: 5, type: "Global", title: "روز جهانی جلوگیری از خودکشی" },
    { holiday: false, month: 10, day: 8, type: "Global", title: "روز جهانی کودک" },
    { holiday: false, month: 10, day: 9, type: "Global", title: "روز جهانی پست" },
    { holiday: false, month: 10, day: 14, type: "Global", title: "روز جهانی استاندارد" },
    { holiday: false, month: 10, day: 15, type: "Global", title: "روز جهانی نابینایان (عصای سفید)" },
    { holiday: false, month: 10, day: 16, type: "Global", title: "روز جهانی غذا" },
    { holiday: false, month: 10, day: 24, type: "Global", title: "روز ملل متحد و روز جهانی توسعه اطلاعات" },
    { holiday: false, month: 10, day: 27, type: "Global", title: "روز جهانی میراث سمعی و بصری" },
    { holiday: false, month: 10, day: 31, type: "Global", title: "روز جهانی شهرها" },
    { holiday: false, month: 10, day: 31, type: "Global", title: "جشن هالووین" },
    { holiday: false, month: 11, day: 6, type: "Global", title: "روز بین‌المللی پیشگیری از سوء استفاده از محیط زیست در جنگ و مناقشات مسلحانه" },
    { holiday: false, month: 11, day: 10, type: "Global", title: "روز جهانی علم در خدمت صلح و توسعه" },
    { holiday: false, month: 11, day: 14, type: "Global", title: "روز جهانی دیابت" },
    { holiday: false, month: 11, day: 21, type: "Global", title: "روز جهانی تلویزیون" },
    { holiday: false, month: 11, day: 25, type: "Global", title: "روز جهانی مبارزه با خشونت علیه زنان" },
    { holiday: false, month: 11, day: 29, type: "Global", title: "روز جهانی همبستگی با مردم فلسطین" },
    { holiday: false, month: 12, day: 1, type: "Global", title: "روز جهانی مبارزه با ایدز" },
    { holiday: false, month: 12, day: 2, type: "Global", title: "روز جهانی لغو برده‌داری" },
    { holiday: false, month: 12, day: 3, type: "Global", title: "روز جهانی معلولین" },
    { holiday: false, month: 12, day: 7, type: "Global", title: "روز جهانی هواپیمایی" },
    { holiday: false, month: 12, day: 10, type: "Global", title: "روز جهانی حقوق بشر" },
    { holiday: false, month: 12, day: 11, type: "Global", title: "روز جهانی کوهستان" },
    { holiday: false, month: 12, day: 18, type: "Global", title: "روز جهانی عاری از خشونت و افراطی‌گری" },
    { holiday: false, month: 12, day: 18, type: "Global", title: "روز جهانی مهاجران" },
    { holiday: false, month: 12, day: 25, type: "Global", title: "ولادت حضرت عیسی مسیح (ع)" }
];
