export const jalaliMonthMap = Object.freeze({
	fa: Object.freeze({
		1: "فروردین",
		2: "اردیبهشت",
		3: "خرداد",
		4: "تیر",
		5: "مرداد",
		6: "شهریور",
		7: "مهر",
		8: "آبان",
		9: "آذر",
		10: "دی",
		11: "بهمن",
		12: "اسفند",
	}),
	en: Object.freeze({
		1: "Farvardin",
		2: "Ordibehesht",
		3: "Khordad",
		4: "Tir",
		5: "Mordad",
		6: "Shahrivar",
		7: "Mehr",
		8: "Aban",
		9: "Azar",
		10: "Dey",
		11: "Bahman",
		12: "Esfand",
	}),
} as const);
